### ISSUE TITLE
[RELEASE] 11.7.0

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#1009]
Release a new version

Xcode version to work with:
12.5

### Git & Code

- [x] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [x] [TRFX] Update translations from transifex branch.
- [ ] [TRFX] Check for missing translations. Ping @cscherm
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [DEV] Update In-App Release Notes (changelog) in ownCloud/Release Notes/ReleaseNotes.plist
- [x] [DEV] Changelog: Created a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD
- [x] [DEV] Changelog: Moved all changelog files from the unreleased folder to the new version folder
- [x] [QA] Design Test plan
- [x] [QA] Regression Test plan
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [ ] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

If it is required to update the iOS-SDK version:

- [x] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code)
- [ ] [mail] inform #marketing about the new release.
- [ ] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [ ] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [ ] [DIS] Upload the binary to the App Store
- [ ] [DIS] App Store Connect: Trigger release (manually)
- [ ] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [ ] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [ ] [DIS] App Store Connect: Update changelogs
- [ ] [DIS] App Store Connect: Submit for review
- [x] Update ownCloud.online Description:
```
Note: This app is intended for use with an active ownCloud Online subscription only. For connecting a self-hosted ownCloud please use our community app.
```

## QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2011.7/Regression.md

BUGS & IMPROVEMENTS:

- [x] (1) App crashes when all accounts are removed https://github.com/owncloud/ios-app/issues/1009#issuecomment-884839274 [FIXED]
- [X] (2) Paste Item via Keyboard Shortcut CMD + V was not working https://github.com/owncloud/ios-app/issues/1009#issuecomment-885556496 [FIXED]
- [X] (3) Crash uploading ~30 files https://github.com/owncloud/ios-app/issues/1009#issuecomment-885590309 [FIXED]
- [X] (4) Background upload notification https://github.com/owncloud/ios-app/issues/1009#issuecomment-885619454 [FIXED]
- [X] (5) Beta label in the background feature https://github.com/owncloud/ios-app/issues/1009#issuecomment-885622292 [FIXED]
- [x] (6) Keyboard shortcuts for X-digit passcode dialog https://github.com/owncloud/ios-app/issues/1009#issuecomment-886662863 [FIXED]
- [X] (7) Spelling error in notification https://github.com/owncloud/ios-app/issues/1009#issuecomment-887253502 [FIXED]
- [x] (8) Crashes in auto uploads https://github.com/owncloud/ios-app/issues/1009#issuecomment-888394685 [FIXED]

**Comment by jesmrec** [comment]
### (1)

as @michaelstingl reported

1. Install app
2. Add accounts
3. Remove accounts

Current: app crashes
Expected: no crash

iPhoneXR v14.6

**Comment by hosy** [comment]
@jesmrec 
(1) is fixed with commit 70f00fa2

**Comment by hosy** [comment]
(2) Paste Item via Keyboard Shortcut `CMD` + `V` was not working

(Already fixed with a802692b)

**Comment by jesmrec** [comment]
### (3)

1. Select `Upload from your photo library` inside any folder of the account
2. Select ~30 pictures and `Add` 

Current: Uploads start. App crashes before everything finishes

Caught log:  [ownCloud_23_Jul_2021_at_13_56_59.log.txt](https://github.com/owncloud/ios-app/files/6868566/ownCloud_23_Jul_2021_at_13_56_59.log.txt)

Expected: Everything uploaded without crash.

NOTE: with ~30 uploads i was able to reproduce several times with two different devices and accounts in two different servers.

iPhoneXR v14.6
iPadAir v13.7
`8a43cd6c4`

**Comment by jesmrec** [comment]
### (4)

Just to know if this behaviour is expected:

1. Settings > Media Uploads
2. Enable `Auto Uploads Photos` and select a correct path to upload
3. Enable `Background refresh`
4. Enable `Background upload notifications`
5. Without closing the oC app, switch to camera app and take some photos

Current: The app is opened (never closed),  but notification with background uploads is displayed
Expected: Is correct that a background notification is shown when the app is in foreground? 

iPhoneXR v14.6
iPadAir v13.7
`8a43cd6c4`

**Comment by jesmrec** [comment]
### (5)

Just a suggestion:

Background uploads were not tested, because the dificulty to cause location changes. For this reason, i'd add a `(BETA)` indicator in the feature label, so that, everyone will know that the feature is experimental at this point:

![Screenshot 2021-07-23 at 15 01 57](https://user-images.githubusercontent.com/14894746/126785351-c8cc3298-ef77-4481-8ee5-38c3654518f4.png)

What do you think?

**Comment by jesmrec** [comment]
### (6)

Using iPad iOS13

1. Attach physical keyboard to the iPad
2. Open Settings
3. Enable Passcode

Current: 4-Digit/6-Digit dialog is displayed correctly. A long press to `CMD` does not show menu to select one of the options. By browsing to any other `Settings` option, menu keeps in the screen and `CMD` shows the options. I hope this video helps to clarify:


https://user-images.githubusercontent.com/14894746/126989208-e157b53f-e4aa-4ce7-bc27-c14de84c9fc4.MP4

Expected: `CMD` long press shows the keyboard shortcuts when they are displayed

iPadAir v13
`144d67e7`

**Comment by jesmrec** [comment]
### (7)

An spelling error:

1. Select 5 items from the file list
2. Select `Copy` and `Copy to clipboard`

Current: Notification with: `5 items **was** copied to the clipboard`

Expected: Notification with: `5 items **were** copied to the clipboard`

iPhoneXR v14.6
´4e415b862´

**Comment by hosy** [comment]
@jesmrec (4) (5) are fixed. 
(4) I changed the title of the notification to "Media Upload", now it is more general.
(5) I added (Lab Version) to the title and I added a subtitle to the "Background refresh" for a better description.

**Comment by jesmrec** [comment]
(4) and (5) fixed!

**Comment by hosy** [comment]
@jesmrec  (7) I cannot reproduce. For me the wording is correct with commit 4e415b8

**Comment by jesmrec** [comment]
i will check again (7).

**Comment by hosy** [comment]
@jesmrec I added the notification to the cut action too. Furthermore I added a note if a folder was copied: 45df5ca

**Comment by jesmrec** [comment]
(7) is reproducible with `144d67e7`, but fixed with `4e415b8`

**Comment by jesmrec** [comment]
> @jesmrec I added the notification to the cut action too. Furthermore I added a note if a folder was copied: [45df5ca](https://github.com/owncloud/ios-app/commit/45df5cad50d40d19205ffa7ddad1cee79d38eacf)

- Notification with `Cut` action is correct

- I do not see the note when the folder is copied to clipboard (`45df5cad`):

https://user-images.githubusercontent.com/14894746/127123617-a2a018c1-a521-4b95-84c9-87c2713f4efa.MP4

**Comment by hosy** [comment]
> > @jesmrec I added the notification to the cut action too. Furthermore I added a note if a folder was copied: [45df5ca](https://github.com/owncloud/ios-app/commit/45df5cad50d40d19205ffa7ddad1cee79d38eacf)
> 
> * Notification with `Cut` action is correct
> * I do not see the note when the folder is copied to clipboard (`45df5cad`). Checking the code, the note should point to the fact that copying a folder to another account/location is not posible. Is that correct?
> 

This note is only visible, if you have at least two accounts configured. Otherwise it does not makes sense. For testing, setup two accounts in the app.

**Comment by hosy** [comment]
@jesmrec (6) is fixed with df7b282

**Comment by jesmrec** [comment]
> This note is only visible, if you have at least two accounts configured. Otherwise it does not makes sense. For testing, setup two accounts in the app.

ok, with more accounts is correct. The point is, copying folders does not work with other locations (Files app, f.ex). Should we add this tip to the message? does it make sense?

**Comment by hosy** [comment]
> > This note is only visible, if you have at least two accounts configured. Otherwise it does not makes sense. For testing, setup two accounts in the app.
> 
> ok, with more accounts is correct. The point is, copying folders does not work with other locations (Files app, f.ex). Should we add this tip to the message? does it make sense?

I added this notice too and now it is always visible (when a folder was copied, no need of two accounts): b19fad2
Is this updated note understandable?

**Comment by jesmrec** [comment]
(6) fixed

**Comment by jesmrec** [comment]
> I added this notice too and now it is always visible (when a folder was copied, no need of two accounts): b19fad2
Is this updated note understandable?

that's perfect. I also noticed that the `ownCloud` word  is brandable. Cool!

**Comment by hosy** [comment]
@jesmrec I also fixed the following:
- changing value of UISwitch was possible, if UI element was disabled (with keyboard commands)
(e.g. `Settings` > `Media Uploads` > `Use Background refresh`)

- moved location updates subtitle for media upload into regarding row

**Comment by jesmrec** [comment]
> @jesmrec I also fixed the following:
> 
> * changing value of UISwitch was possible, if UI element was disabled (with keyboard commands)
>   (e.g. `Settings` > `Media Uploads` > `Use Background refresh`)

👍 

> * moved location updates subtitle for media upload into regarding row

👍 

Both are correct

**Comment by hosy** [comment]
@jesmrec please can you check on your device if you find the crash report, which happened after the mass media upload crash and attach it here for @felix-schwarz ?

**Comment by jesmrec** [comment]
no logs in the device :( 

but, the crash is easy to reproduce on my side. I use an archived .ipa, and with the steps of (3), it happens.

**Comment by felix-schwarz** [comment]
@jesmrec I found a crash uploading 20+ images and fixed it with e44a083. Please check if you can still reproduce (3).

**Comment by jesmrec** [comment]
Checking `e44a083` with sdk `f9d7fd3` 

With ~20-30 files, no crash happens.

Increasing the number of files to upload to ~50, crashes happen again. The bigger the number, more crashes happen

iPhoneXR v14.7.1

**Comment by felix-schwarz** [comment]
@jesmrec Thanks for the XC archive and the log. d476ba2 should fix that crash.

**Comment by jesmrec** [comment]
With app `d476ba2` sdk `f9d7fd3`:

- Manual uploads: crashes are gone when a big number of files is uploaded : ✅ 

- Manual uploads: with the big number of files, repetitions happen. ~5% for big number of uploads ❌ 

- Automatic uploads: Crash happens:

### (8)

1. Enable `Media Uploads` > `Auto Upload Photos` and select a correct folder as destination
2. Take 50 photos with the camera
3. Open the app 

Current: crashes happen in the same way as [(3)](https://github.com/owncloud/ios-app/issues/1009#issuecomment-885590309)

Expected: no crashes

**Comment by felix-schwarz** [comment]
@jesmrec Regarding repeated imports, I found an edge case where the media import action could import an asset more than once and addressed as of 1fba0838888e698dc5b496b74609e9ce9cfbb51d.

Regarding the crash on automatic import: I could not reproduce it. Please share the (crash) log and the corresponding xcarchive, so I can symbolicate the crash log and see where the crash happens.

**Comment by jesmrec** [comment]
Repetitions do not happen anymore

**Comment by felix-schwarz** [comment]
@jesmrec (8) should be addressed as of 0c76108.

**Comment by jesmrec** [comment]
(8) is fixed

Checking upgrades. If it works fine, release is ready to go

**Comment by jesmrec** [comment]
Release is approved on my side

Approved commits:

app: `0c76108`
apk: `f9d7fd3`

Xcode version: `12.5 (12E262)`

Devices used:

iPhoneXR v14.7.1
iPadAir v13.7

great work, team!!
