### ISSUE TITLE
[FEATURE REQUEST] Create Branded Screenshots

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#1013]
Currently branded screenshots are working for `ownCloud online`. But it needs to extend the support for special branding cases:

### TASKS

- [ ] branded client will be delivered with server URL (URL bar is not available)
- [ ] branded client can add accounts (different server list is showing)
- [ ] back button `Manage` is not available
- [ ] add a new fastlane lane for the branding clients to create screenshots (without framing)
