### ISSUE TITLE
[RELEASE] 11.8.0

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#1062]
Release a new version

Xcode version to work with: `12.5.1 (12E507)`

### Git & Code

- [x] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [ ] [TRFX] Update translations from transifex branch.
- [ ] [TRFX] Check for missing translations. Ping @cscherm
- [ ] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [DEV] Update In-App Release Notes (changelog) in ownCloud/Release Notes/ReleaseNotes.plist
- [x] [DEV] Changelog: Created a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD
- [x] [DEV] Changelog: Moved all changelog files from the unreleased folder to the new version folder
- [x] [QA] Design Test plan
- [x] [QA] Regression Test plan
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)
- [ ] [DEV] ownBrander: Update the ownBrander git tag in repository `customer_portal` to new release tag
- [ ] [DEV] Update used Xcode version for the release in [.xcode-version](https://github.com/owncloud/ios-app/blob/master/.xcode-version)
- [ ] [DEV] Inform #documentation about the new release to set new documentation branch tag

If it is required to update the iOS-SDK version:

- [x] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code)
- [ ] [mail] inform #marketing about the new release.
- [ ] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [ ] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [ ] [DIS] Upload the binary to the App Store
- [ ] [DIS] App Store Connect: Trigger release (manually)
- [ ] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [ ] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [ ] [DIS] App Store Connect: Update changelogs
- [ ] [DIS] App Store Connect: Submit for review

## QA

Regression test plan: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2011.8/Regression.md

BUGS & IMPROVEMENTS:

- [x] (1) Colors missed in cards https://github.com/owncloud/ios-app/issues/1062#issuecomment-976562111 [WONT FIX]
- [x] (2) Color in multiselection circle https://github.com/owncloud/ios-app/issues/1062#issuecomment-976570871 [FIXED]
- [x] (3) (improvement) Glitch when connecting the first account https://github.com/owncloud/ios-app/issues/1062#issuecomment-976582667 [FIXED]
- [x] (4) Color in dialog https://github.com/owncloud/ios-app/issues/1062#issuecomment-976595773 [FIXED]
- [x] (5) Bottom side in folder picker of camera uploads https://github.com/owncloud/ios-app/issues/1062#issuecomment-977721745 [WONT FIX - Xcode13/SDK15 related]
- [X] (6) IAP section hidden https://github.com/owncloud/ios-app/issues/1062#issuecomment-977733307 [MOVED TO https://github.com/owncloud/ios-app/issues/1063]
- [x] (7) Server URL and bookmark name are lost https://github.com/owncloud/ios-app/issues/1062#issuecomment-977747010 [WONT FIX]
- [x] (8) Delete local copies not working https://github.com/owncloud/ios-app/issues/1062#issuecomment-977803076 [not always reproducible - will monitor this]
- [X] (9) Settings access duplicated https://github.com/owncloud/ios-app/issues/1062#issuecomment-978027998 [FIXED]
- [x] (10) "Open in Window" missing https://github.com/owncloud/ios-app/issues/1062#issuecomment-978943651 [FIXED]
- [x] (11) Table incorrect in split mode (iPad) https://github.com/owncloud/ios-app/issues/1062#issuecomment-979282618 [FIXED]

**Comment by jesmrec** [comment]
### (1)

Blue color lost somewhere:

|| 11.7.1 | Current |
|:-:|:-:|:-:|
|**Actions card**|![Screenshot 2021-11-23 at 14 43 14](https://user-images.githubusercontent.com/14894746/143035264-4efa927c-8a99-4fcd-b5eb-6715685e988b.png)|<img width="341" alt="Screenshot 2021-11-23 at 14 44 04" src="https://user-images.githubusercontent.com/14894746/143035427-f0ef33ad-9487-4075-bac3-b9b5aa221b4b.png">|
|**Files card**|![Screenshot 2021-11-23 at 14 46 20](https://user-images.githubusercontent.com/14894746/143035614-4ed634ba-e0e4-4705-a349-e15577716161.png)|<img width="344" alt="Screenshot 2021-11-23 at 14 46 57" src="https://user-images.githubusercontent.com/14894746/143035715-0d8175f5-fffb-40a3-aaff-93ea031b8c9b.png">|

**Comment by jesmrec** [comment]
### (3) (improvement)

After adding the first account, new only-one-account view is displayed after showing during a while the old bookmark list. In the sec 12 of the following video

https://user-images.githubusercontent.com/14894746/143038226-4a39367d-1cb1-40b3-9439-10b924caf5b1.MP4

Could this effect be mitigated?

iPhoneXR v15.1
`34571cdb9`

**Comment by jesmrec** [comment]
### (4)

Same as (1) and/or (2)? i think so, but just in case:

|| 11.7.1 | Current |
|:-:|:-:|:-:|
| **Dialog** | ![Screenshot 2021-11-23 at 15 11 34](https://user-images.githubusercontent.com/14894746/143039976-ae013d7f-1d03-4fe1-af33-1aeb45f4259a.png)  |<img width="246" alt="Screenshot 2021-11-23 at 15 12 28" src="https://user-images.githubusercontent.com/14894746/143039894-2a262b07-58d3-4fdf-b866-af9102bc6e6c.png">|


NOTE: Screenshot from dark mode, but light mode and classic mode also with the incorrect colors

iPhoneXR v15.1
`34571cdb9`

**Comment by jesmrec** [comment]
### (5)

1. Go to Settings > Media Upload
2. Enable Auto Uploads Pictures
3. Select account
4. Browse to any folder in the selected account

Current:

Folder picker does not cover the whole screen. On the bottom, the Settings view overlaps:

https://user-images.githubusercontent.com/14894746/143217121-c89ee17b-9ad3-4a68-8601-422c8f7efcb7.MP4

Expected:

No such effect

iPhoneXR v15.1
`724edf61`

**Comment by jesmrec** [comment]
### (6)

Did something change in the conditions to display the IAP section in Settings? 

I observed the following situations (all of them are different and isolated cases, not a row of steps):

- If a non-enterprise server is attached -> IAP not visible in Settings
- If a non-enterprise server && an enterpriser server is attached -> IAP not visible in Settings
- If a enterprise server is attached -> IAP not visible in Settings -> IAP not visible in Settings. (damken cloud)
- If `ocis.owncloud.works` is attached -> IAP visible in Settings 
-If `ocis.owncloud.works` is attached together with any other account -> IAP visible in Settings 

Need to clarify the expected behaviour

NOTE: app built with Xcode

iPhoneXR v15.1
`724edf61`

**Comment by jesmrec** [comment]
### (7)

Just to know if the following is the expected:

I realised that the new presentation view for one account does not refer 

 - The server URL
 - The bookmark name

You see only your display name

**11.7.1** -> Bookmark name && server url. If bookmark name'd not exist, Displayname@serverURL instead
**Current** -> Only displayname. Bookmark name and server URL missed.

Is that the expected?

Let's compare with a couple of screenshots:

|| 11.7.1 | Current |
|:-:|:-:|:-:|
| | <img width="316" alt="Screenshot 2021-11-24 at 11 30 44" src="https://user-images.githubusercontent.com/14894746/143221741-3a5aabeb-37dc-448f-8b6f-abe0c3621179.png"> | <img width="328" alt="Screenshot 2021-11-24 at 11 23 28" src="https://user-images.githubusercontent.com/14894746/143220993-890302c1-cccf-47ee-b357-4710c092ed65.png"> |


iPhoneXR v15.1
`724edf61`

**Comment by jesmrec** [comment]
### (8)

1. Download some images or files
2. Go to bookmark list and swipe to select `Manage`
3. Select `Delete all offline Files`

Current:

Files are not deleted. Check the following video. Images are not marked as "not downloaded" and size of the account does not decrease after clicking the option:

https://user-images.githubusercontent.com/14894746/143232956-e835947d-8f7a-468a-be6d-44c7735e6a98.MP4

Expected: All downloaded stuff deleted (but the av. offline)

iPhoneXR v15.1
`724edf61`

**Comment by hosy** [comment]
@jesmrec in my opinion we cannot use Xcode 13, because it is building against the iOS 15 SDK. But: Xcode 12.5.1 is not running on macOS 12. So we need to build it on macOS 11.
We have some issues in this version with iOS 15, which are currently not resolved.

**Comment by hosy** [comment]
@jesmrec yes, please test with 12.5.1

**Comment by jesmrec** [comment]
After re-checking all the reports with a new Xcode 12.5.1 build, only the (5) is not reproducible anymore.

**Comment by jesmrec** [comment]
### (9)

`Settings` is duplicated in the one-account-presentation view:

![Screen Shot 2021-11-24 at 17 17 04](https://user-images.githubusercontent.com/14894746/143275554-c0e22cb3-0228-44b9-acd5-2fbbf7f46434.png)

iPhoneXR v15.1
`724edf61`

**Comment by jesmrec** [comment]
### (10)

As (7), other missing option is the "open in window" for iPads.

Expected?

iParAir v14
`724edf61`

**Comment by hosy** [comment]
> ### (6)
> Did something change in the conditions to display the IAP section in Settings?
> 
> I observed the following situations (all of them are different and isolated cases, not a row of steps):
> 
> * If a non-enterprise server is attached -> IAP not visible in Settings
> * If a non-enterprise server &&  enterprise server is attached -> IAP not visible in Settings
> * If a enterprise server is attached -> IAP not visible in Settings (damken cloud)
> * If `ocis.owncloud.works` is attached -> IAP visible in Settings
> * If `ocis.owncloud.works` is attached together with any other account -> IAP visible in Settings
> 
> Need to clarify the expected behaviour
> 
> NOTE: app built with Xcode, no archived ipa.
> 
> iPhoneXR v15.1 `724edf61`

I think currently there is no differentiation between enterprise and non-enterprise yet. Please can you add an issue for this, so that we can handle ocis non-enterprise and enterprise, when available?

**Comment by hosy** [comment]
> ### (7)
> Just to know if the following is the expected:
> 
> I realised that the new presentation view for one account does not refer
> 
> * The server URL
> * The bookmark name
> 
> You see only your display name
> 
> **11.7.1** -> Bookmark name && server url. If bookmark name'd not exist, Displayname@serverURL instead **Current** -> Only displayname. Bookmark name and server URL missed.
> 
> Is that the expected?
> 
> Let's compare with a couple of screenshots:
> 
> 11.7.1	Current
> <img alt="Screenshot 2021-11-24 at 11 30 44" width="316" src="https://user-images.githubusercontent.com/14894746/143221741-3a5aabeb-37dc-448f-8b6f-abe0c3621179.png">	<img alt="Screenshot 2021-11-24 at 11 23 28" width="328" src="https://user-images.githubusercontent.com/14894746/143220993-890302c1-cccf-47ee-b357-4710c092ed65.png">
> iPhoneXR v15.1 `724edf61`

Thanks for having a look at this details. Yes, this is expected and it should not be shown in this "non-expert" view. This details can be seen in the bookmark view. For me this is ok without fixing it.

**Comment by hosy** [comment]
## (11)

Found another one, when putting the iPad app into split view.  As a result the table view gets a wrong size:


https://user-images.githubusercontent.com/736109/143463709-2b776d81-9fe2-42d4-934c-6007ae16cfab.mp4

**Comment by hosy** [comment]
@jesmrec 2,3,4,9,10,11 are fixed and can now be tested.
1: the current color is ok
5: Xcode 13 issue, will be fixed in next release
6: please add a new issue, as described above
7: the current behavior is ok
8: @felix-schwarz please can you have a look?

**Comment by jesmrec** [comment]
After checking the fixes:

1, 5, 7 -> wont fix
2, 3, 4, 10, 11 -> fixed

6 -> i'll add a new issue. Users will be able to purchase only from the file list
9 -> fixed for iPhone, but not for iPad CC @hosy 

So, ftm only (8) and (9) requires attention

**Comment by hosy** [comment]
@jesmrec (9) is fixed on the iPad too. Please have a look again.

**Comment by felix-schwarz** [comment]
@jesmrec Re (8): I can't reproduce the issue with a new account.

Is this an account you've used for testing development versions in the past - or a fresh account?

If it's the former, it might explain it, as development versions may have leaked temporary files in the past, to which now there's no longer a reference, so they aren't "visible" to the storage management.

If it's the latter (fresh account), I'll need to take a closer look.

**Comment by jesmrec** [comment]
@felix-schwarz about (8)

- I reproduced it with a fresh install, using an archived ipa (the latest i built over `f07912b2`). I can provide the ipa
- in iOS14 is not reproduced, only iOS15.
- It happens, but not in the same way. If you have a folder with 10 files, download them and them delete offline files, sometimes are 6, other 5, other 8... not the same result.
- The easiest way to reproduce is using videos: 
   1. Create a folder
   2. Upload 10 videos inside
   3. Delete offline copies

i hope it helps. in case you don't reproduce it, it's not a problem for me to move to a separate issue and deal with it in the following release. Not a bad blocker.

**Comment by felix-schwarz** [comment]
@jesmrec I followed your steps with 8 small video files (upload via browser) on an iPhone 12 mini running the latest iOS version and the same commit as you were running, but couldn't reproduce the issue.

Do you use the same SDK version?
![Bildschirmfoto 2021-11-29 um 12 21 02](https://user-images.githubusercontent.com/639669/143860050-cc7dd4cd-898b-4e8d-aa93-e9d58319201d.jpeg)

Does it clear all files after rebooting the device?

Since I can't reproduce it, to me this seems like some corner case or special scenario we should look into, but that shouldn't block the release.

**Comment by jesmrec** [comment]
> @jesmrec Regarding (8) I followed your steps with 8 small video files (upload via browser) on an iPhone 12 mini running the latest iOS version and the same commit as you were running, but couldn't reproduce the issue.
> 
> Do you use the same SDK version? ![Bildschirmfoto 2021-11-29 um 12 21 02](https://user-images.githubusercontent.com/639669/143860050-cc7dd4cd-898b-4e8d-aa93-e9d58319201d.jpeg)
> 
> Does it clear all files after rebooting the device?
> 
> Since I can't reproduce it, to me this seems like some corner case or special scenario we should look into, but that shouldn't block the release.

yes, versions are correct on my side. 

After rebooting: it works fine the first time, then it becomes again unstable.

Will not block the release

**Comment by jesmrec** [comment]
Release is approved on my side.

Approved commits:

app: `f07912b`
sdk: `05c8b27`

Xcode version: `12.5.1 (12E507)`

Scenarios tested autom:
https://github.com/owncloud/ios-scenario-testing/tree/master/src/test/resources/io/cucumber
with results:
[serenity_iOS10.8.zip](https://github.com/owncloud/ios-app/files/7618010/serenity_iOS10.8.zip)

Devices:

iPhoneXR, iOS v15.1
iPadAir2, iPadOS v14.7

Great job, team!
