### ISSUE TITLE
Files app 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#11]
__As user, i want to manage files using 3rp party apps through Files app__

Epic for all features related with Files App. Smaller issues will be created to build the feature in an incremental way

- [x] Research about performance
- [x] Research Swift vs Obj-C in File Provider to handle memory
- [x] Add extension Files app
- [x] New App Id
- [x] Update set up file
- [x] Show list of files 
- [x] Save files by opening from 3rd party
- [X] Create files from 3rd party app

Features related:

- [x] Browse through ownCloud folders (including multiaccount)
- [x] Open ownCloud file
- [x] Save opened file
- [x] Save in oC created file
- [x] Multiaccount https://github.com/owncloud/ios-app/issues/7#issuecomment-388300629
- [x] Basic operations: Copy, Duplicate, Move, Delete, ~~Share~~ , Download, Rename
- [ ] Copy files between storage providers https://github.com/owncloud/ios-app/issues/361
- [ ] oC Sharing via iOS Files app
- [ ] oC Favorites via iOS Files app
- [ ] Working Set ([developer docs](https://developer.apple.com/documentation/fileprovider/content_and_change_tracking/defining_your_file_provider_s_content#2897861), wait for major changes in FileProvider in Spring 2020, open PR: https://github.com/owncloud/ios-app/pull/338)
  - [ ] Recent items
  - [ ] iOS Tags
  - [ ] iOS Favorites
  - [ ] Recently deleted items

**Comment by michaelstingl** [comment]
Multi account: https://github.com/owncloud/ios-app/issues/7#issuecomment-388300629

**Comment by felix-schwarz** [comment]
Files app integration is implemented at this point.
