### ISSUE TITLE
[FEATURE REQUEST] update the 3 year old spec files in enterprise/MDM/AppConfig

### ISSUE THREAD

**Issue by Ceelight** [owncloud/ios-app#1251]
**Is your feature request related to a problem? Please describe.**
Since the changes made in MDM config for version 12 of the app, the old configs enrolled on devices are not working anymore. I tried to adapt to the new key names, but the app V12.0.2 is not taking the default-url.

**Describe the solution you'd like**
Please update the 3 year old spec files in enterprise/MDM/AppConfig

**Describe alternatives you've considered**

**Additional context**

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
All parameters documented here:
https://doc.owncloud.com/ios-app/next/appendices/mdm.html
(Always fresh, autogenerated from the source code)

**Comment by michaelstingl** [comment]
I'd tend to remove the handcrafted examples:
- https://github.com/owncloud/ios-app/pull/1252

**Comment by Ceelight** [comment]
> https://doc.owncloud.com/ios-app/next/appendices/mdm.html

Thanks! I've seen that and changed our very simple xml template accordingly. But it doesn't work. The app is not prefilling the server URL.
`<managedAppConfiguration>
	<version>1</version>
	<bundleId>com.owncloud.ios-app</bundleId>
	<dict>
		<string keyName="account-settings.default-url">
			<defaultValue>
				<value>ios.owncloud-demo.com</value>
			</defaultValue>
		</string>
		<boolean keyName="account-settings.url-editable">
		</boolean>
	</dict>
	<presentation defaultLocale="en-US">
	<fieldGroup>
		<name>
			<language value="en-US">Bookmark Setttings</language>
		</name>
		<field keyName="account-settings.default-url" type="input">
			<label>
				<language value="en-US">Default Server URL</language>
			</label>
			<description>
				<language value="en-US">Allows to define default server URL</language>
			</description>
		</field>
		<field keyName="account-settings.url-editable" type="checkbox">
			<label>
				<language value="en-US">Server URL changeable</language>
			</label>
			<description>
				<language value="en-US">Enables or disables changing server URL</language>
			</description>
		</field>
	</fieldGroup>
	</presentation>
</managedAppConfiguration>`

Any idea what could be wrong here? I changed from bookmark.default-url to account-settings.default-url. That's all.
Thanks!

**Comment by Ceelight** [comment]
Thanks Michael! Our MDM ist BlackBerry UEM which wants "appconfig code". plist doesn't work here.

But I know what I could try next. I'll report then... Thanks again!

**Comment by michaelstingl** [comment]
For me, this `PLIST` worked in Xcode:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>account-settings.default-url</key>
	<string>https://demo.owncloud.com</string>
	<key>account-settings.url-editable</key>
	<false/>
</dict>
</plist>
```

You could also consider:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>branding.profile-url</key>
	<string>https://demo.owncloud.com</string>
	<key>branding.can-add-account</key>
	<false/>
	<key>branding.profile-allow-url-configuration</key>
	<false/>
	<key>branding.can-edit-account</key>
	<false/>
</dict>
</plist>
```

**Comment by Ceelight** [comment]
Thanks a lot Michael! I'll try this tomorrow and will give feedback.

**Comment by Ceelight** [comment]
Both of above exaamples don't work unfortunately. I must use the app config data format like my example above. Otherwise UEM Server says it's not valid.

I found the following in the log:
`2023-07-14 11:31:25.238000+0200 ownCloud[632.033902] [dbug] | [IPNC] Adding observer=<OCBookmark: 0x282080000, uuid: 56653DB8-610F-46FD-BF5D-2C08C967ADA3, databaseVersion: 2, userInfo: {\n    "bookmark-creation" =     {\n        "app-build-number" = 270;\n        "app-version" = "12.0.2";\n        "creation-date" = "2023-07-14 09:31:25 +0000";\n        "log-intro" = "Host: com.owncloud.ios-app 12.0.2 (270) # - milestone/12.0.2@46e7082; SDK: 12.0.2 (270) #e301f3d; OS: iPadOS 16.5; Device: iPad (iPad13,10); Localizations: [de]; Class Setttings: action.allowed: default: `( )` -> computed: `( )`\naction.create-document-mode: reg-default: `create-and-open` -> computed: `create-and-open`\naction.disallowed: default: `( )` -> computed: `( )`\nhttp.user-agent: default: `ownCloudApp/{{app.version}} ({{app.part}}/{{app.build}}; {{os.name}}/{{os.version}}; {{device.model}})` -> computed: `ownCloudApp/{{app.version}} ({{app.part}}/{{app.build}}; {{os.name}}/{{os.version}}; {{device.model}})`\ncore.thumbnail-available-for-mime-type-prefixes: default: `(     \"*\" )` -> computed: `(     \"*\" )`\ncore.cookie-support-enabled: default: `1` -> computed: `1`\nauthentication.browser-session-class: default: `operating-system` -> computed: `operating-system`\nauthentication.browser-session-prefers-ephermal: default: `0` -> computed: `0`\nlog.format: default: `text` -> computed: `text`\nlog.single-lined: default: `0` -> computed: `0`\nlog.privacy-mask: default: `0` -> computed: `0`\nlog.colored: default: `0` -> computed: `0`\nlog.level: default: `4` -> user-prefs: `0` -> computed: `0`\nlog.maximum-message-size: default: `0` -> computed: `0`\nlog.replace-newline: default: `1` -> computed: `1`\nlog.enabled-components: default: `(     \"writer.stderr\",     \"writer.file\" )` -> computed: `(     \"writer.stderr\",     \"writer.file\" )`\nlog.blank-filtered-messages: default: `0` -> computed: `0`\nlog.synchronous: default: `0` -> computed: `0`\nbranding.enable-review-prompt: reg-default: `0` -> computed: `0`\nbranding.url-privacy: reg-default: `https://owncloud.org/privacy-policy/` -> computed: `https://owncloud.org/privacy-policy/`\nbranding.send-feedback-address: reg-default: `ios-app@owncloud.com` -> computed: `ios-app@owncloud.com`\nbranding.can-add-account: reg-default: `1` -> computed: `1`\nbranding.url-help: reg-default: `https://owncloud.com/docs-guides/` -> computed: `https://owncloud.com/docs-guides/`\nbranding.can-edit-account: reg-default: `1` -> computed: `1`\nbranding.url-documentation: reg-default: `https://doc.owncloud.com/ios-app/latest/` -> computed: `https://doc.owncloud.com/ios-app/latest/`\nbranding.url-terms-of-use: reg-default: `https://raw.githubusercontent.com/owncloud/ios-app/master/LICENSE` -> computed: `https://raw.githubusercontent.com/owncloud/ios-app/master/LICENSE`\nextensions.disallowed: default: `( )` -> computed: `( )`\nconnection.force-background-url-sessions: default: `0` -> computed: `0`\nconnection.minimum-server-version: default: `10.0` -> computed: `10.0`\nconnection.allow-cellular: default: `1` -> computed: `1`\nconnection.preferred-authentication-methods: default: `(     \"com.owncloud.openid-connect\",     \"com.owncloud.oauth2\",     \"com.owncloud.basicauth\" )` -> computed: `(     \"com.owncloud.openid-connect\",     \"com.owncloud.oauth2\",     \"com.owncloud.basicauth\" )`\nconnection.allow-background-url-sessions: default: `1` -> computed: `1`\nconnection.plain-http-policy: default: `warn` -> computed: `warn`\nconnection.always-request-private-link: default: `0` -> computed: `0`\nconnection.transparent-temporary-redirect: default: `0` -> computed: `0`\n; Log options: level=Debug, destinations=[\"writer.stderr\", \"writer.file\"], options=[\"option.log-requests-and-responses\", \"option.log-file-operations\"], maskPrivateData=false";\n        "sdk-commit" = e301f3d;\n        "sdk-version" = "12.0.2 (270) #e301f3d";\n    };\n}> for 'com.owncloud.bookmark.auth-update' [OCIPNotificationCenter.m:99|FULL]
2023-07-14 11:31:25.242000+0200 ownCloud[632.033902] [dbug] | [Keychain, Read] No item found for 56653DB8-610F-46FD-BF5D-2C08C967ADA3:authenticationData [OCKeychain.m:97|FULL]
2023-07-14 11:31:25.256000+0200 ownCloud[632.033902] [info] | [OS] -canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "Der Vorgang konnte nicht abgeschlossen werden. (OSStatus-Fehler -10814.)" [NSLog:0|FULL]
2023-07-14 11:31:27.956000+0200 ownCloud[632.033902] [dbug] | [IPNC] Removing observer=<OCBookmark: 0x282080000, uuid: 56653DB8-610F-46FD-BF5D-2C08C967ADA3, databaseVersion: 2, userInfo: {\n    "bookmark-creation" =     {\n        "app-build-number" = 270;\n        "app-version" = "12.0.2";\n        "creation-date" = "2023-07-14 09:31:25 +0000";\n        "log-intro" = "Host: com.owncloud.ios-app 12.0.2 (270) # - milestone/12.0.2@46e7082; SDK: 12.0.2 (270) #e301f3d; OS: iPadOS 16.5; Device: iPad (iPad13,10); Localizations: [de]; Class Setttings: action.allowed: default: `( )` -> computed: `( )`\naction.create-document-mode: reg-default: `create-and-open` -> computed: `create-and-open`\naction.disallowed: default: `( )` -> computed: `( )`\nhttp.user-agent: default: `ownCloudApp/{{app.version}} ({{app.part}}/{{app.build}}; {{os.name}}/{{os.version}}; {{device.model}})` -> computed: `ownCloudApp/{{app.version}} ({{app.part}}/{{app.build}}; {{os.name}}/{{os.version}}; {{device.model}})`\ncore.thumbnail-available-for-mime-type-prefixes: default: `(     \"*\" )` -> computed: `(     \"*\" )`\ncore.cookie-support-enabled: default: `1` -> computed: `1`\nauthentication.browser-session-class: default: `operating-system` -> computed: `operating-system`\nauthentication.browser-session-prefers-ephermal: default: `0` -> computed: `0`\nlog.format: default: `text` -> computed: `text`\nlog.single-lined: default: `0` -> computed: `0`\nlog.privacy-mask: default: `0` -> computed: `0`\nlog.colored: default: `0` -> computed: `0`\nlog.level: default: `4` -> user-prefs: `0` -> computed: `0`\nlog.maximum-message-size: default: `0` -> computed: `0`\nlog.replace-newline: default: `1` -> computed: `1`\nlog.enabled-components: default: `(     \"writer.stderr\",     \"writer.file\" )` -> computed: `(     \"writer.stderr\",     \"writer.file\" )`\nlog.blank-filtered-messages: default: `0` -> computed: `0`\nlog.synchronous: default: `0` -> computed: `0`\nbranding.enable-review-prompt: reg-default: `0` -> computed: `0`\nbranding.url-privacy: reg-default: `https://owncloud.org/privacy-policy/` -> computed: `https://owncloud.org/privacy-policy/`\nbranding.send-feedback-address: reg-default: `ios-app@owncloud.com` -> computed: `ios-app@owncloud.com`\nbranding.can-add-account: reg-default: `1` -> computed: `1`\nbranding.url-help: reg-default: `https://owncloud.com/docs-guides/` -> computed: `https://owncloud.com/docs-guides/`\nbranding.can-edit-account: reg-default: `1` -> computed: `1`\nbranding.url-documentation: reg-default: `https://doc.owncloud.com/ios-app/latest/` -> computed: `https://doc.owncloud.com/ios-app/latest/`\nbranding.url-terms-of-use: reg-default: `https://raw.githubusercontent.com/owncloud/ios-app/master/LICENSE` -> computed: `https://raw.githubusercontent.com/owncloud/ios-app/master/LICENSE`\nextensions.disallowed: default: `( )` -> computed: `( )`\nconnection.force-background-url-sessions: default: `0` -> computed: `0`\nconnection.minimum-server-version: default: `10.0` -> computed: `10.0`\nconnection.allow-cellular: default: `1` -> computed: `1`\nconnection.preferred-authentication-methods: default: `(     \"com.owncloud.openid-connect\",     \"com.owncloud.oauth2\",     \"com.owncloud.basicauth\" )` -> computed: `(     \"com.owncloud.openid-connect\",     \"com.owncloud.oauth2\",     \"com.owncloud.basicauth\" )`\nconnection.allow-background-url-sessions: default: `1` -> computed: `1`\nconnection.plain-http-policy: default: `warn` -> computed: `warn`\nconnection.always-request-private-link: default: `0` -> computed: `0`\nconnection.transparent-temporary-redirect: default: `0` -> computed: `0`\n; Log options: level=Debug, destinations=[\"writer.stderr\", \"writer.file\"], options=[\"option.log-requests-and-responses\", \"option.log-file-operations\"], maskPrivateData=false";\n        "sdk-commit" = e301f3d;\n        "sdk-version" = "12.0.2 (270) #e301f3d";\n    };\n}> for 'com.owncloud.bookmark.auth-update' [OCIPNotificationCenter.m:125|FULL]`

It tries to add a bookmark, but then there's an error regarding password management and the Bookmark gets removed immediately. Is this the right interpretation here?

**Comment by michaelstingl** [comment]
Looks like nothing was configured from MDM. I'll check in JAMF.

**Comment by michaelstingl** [comment]
Worked fine for me in JAMF:

![CleanShot 2023-07-14 at 12 53 38@2x](https://github.com/owncloud/ios-app/assets/214010/6914635e-068b-4302-abd6-c4f17545a3b6)

![IMG_0052](https://github.com/owncloud/ios-app/assets/214010/d6300bd8-4264-49eb-bb9f-281994852def) | ![IMG_0054](https://github.com/owncloud/ios-app/assets/214010/f71ad9b0-5f6f-45c5-a947-2299121a9c55) | ![IMG_0053](https://github.com/owncloud/ios-app/assets/214010/df03d3d3-92a5-43ee-8eeb-35fafd2e6992)
-- | -- | --
MDM push received | after restart | new config

**Comment by michaelstingl** [comment]
In the logs, you can see how the managed config overrides the default config:

```
branding.can-edit-account: reg-default: `1` -> managed: `0` -> computed: `0`
```

<img width="1263" alt="CleanShot 2023-07-14 at 15 44 30@2x" src="https://github.com/owncloud/ios-app/assets/214010/7178447f-855b-4cb4-8a1f-e48218304340">
