### ISSUE TITLE
[FEATURE REQUEST] Skip account selection when only a one account is configured

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#1288]
**Is your feature request related to a problem? Please describe.**
In the iOS app, every time files are uploaded for instance from the Photos app, the user selection dialog appears, even when only a single user is configured or should be configured.

**Describe the solution you'd like**
It would be more user-friendly if, in the case of a single configured account, this dialog was omitted, and instead, the directory selection prompt appeared directly.

**Describe alternatives you've considered**
n.a.

**Additional context**

![CleanShot 2023-11-10 at 18 28 52](https://github.com/owncloud/ios-app/assets/214010/131956cd-9095-4d27-8ec2-33febca98323)

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
Feedback from sprint reviews:
- [ ] (1) Auto-expand the "Quick access"

**Comment by michaelstingl** [comment]
Superseded by:
- https://github.com/owncloud/ios-app/issues/1311
