### ISSUE TITLE
[RELEASE] 12.2

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#1346]
Release a new version

Xcode version to work with: 15.3 (15E204a)

### Git & Code

- [x] [GIT] Create branch `release/12.2` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [x] [TRFX] Update translations from transifex branch.
- [x] [TRFX] Check for missing translations.
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [DEV] Update In-App Release Notes (changelog) in ownCloud/Release Notes/ReleaseNotes.plist
- [x] [DEV] Changelog: Created a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD
- [x] [DEV] Changelog: Moved all changelog files from the unreleased folder to the new version folder
- [x] [DEV] Inform Documentation-Team for the upcoming major/minor release with new version tag (notify #documentation-internal)
- [x] [QA] Design Test plan
- [x] [QA] Regression Test plan
- [ ] [DOC] Update https://owncloud.com/mobile-apps/#ios version numbers (notify #marketing)
- [ ] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)
- [ ] [DEV] ownBrander: Update the ownBrander git tag in repository `customer_portal` to new release tag
- [x] [DEV] Update used Xcode version for the release in [.xcode-version](https://github.com/owncloud/ios-app/blob/master/.xcode-version)
- [ ] [DEV] Inform #documentation about the new release to set new documentation branch tag

If it is required to update the iOS-SDK version:

- [ ] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code)
- [ ] [mail] inform #marketing about the new release.
- [ ] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [ ] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [ ] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [ ] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [x] [DIS] Upload the binary to the App Store
- [x] [DIS] App Store Connect: Trigger release (manually)
- [x] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [ ] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [x] [DIS] App Store Connect: Update changelogs
- [x] [DIS] App Store Connect: Submit for review

**Comment by jesmrec** [comment]
QA checks (smoke)

- [X] Basic auth 
- [X] OAuth2
- [X] OIDC
- [X] Transfers (upload/download)
- [X] Security settings
- [X] Share with oC from 3rd party
- [X] Files app

Changelog

- [X] Av. offline badge https://github.com/owncloud/ios-app/issues/1128
- [X] App provider message when no accounts https://github.com/owncloud/ios-app/pull/1306
- [X] Disable edit mode in markup https://github.com/owncloud/ios-app/pull/1309
- [X] New account wizard https://github.com/owncloud/ios-app/pull/1274
- [X] Image recognition https://github.com/owncloud/ios-app/pull/1283
- [X] Preserve file extension https://github.com/owncloud/ios-app/issues/1292
- [X] New option "add to ownCloud" https://github.com/owncloud/ios-app/issues/1293
- [X] Link naming https://github.com/owncloud/ios-app/pull/1297

Update testing

- [ ] Update from 12.1 (release notes, app version in settings)

**Comment by jesmrec** [comment]
This is approved from my side

**Approved commits:**

app: `74e9492f`
sdk: `d4caa6d`

**Devices:**

iPhone XR v17.4
iPadPro v16

**Autom test executions:**

[vs oCIS 5.0.1](https://reports.cucumber.io/reports/37c27e3b-fe26-4ef0-b526-7864e712df01)
[vs oC 10.14.0](https://reports.cucumber.io/reports/876e2814-c23d-40ac-88c3-32c109424462)

Great job, team!! 🚀
