### ISSUE TITLE
[RELEASE] 12.3

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ios-app#1362]
Release a new version

Xcode version to work with: `16.0 (16A242d)`

### Git & Code

- [x] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [x] [TRFX] Update translations from transifex branch.
- [x] [TRFX] Check for missing translations.
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [DEV] Update In-App Release Notes (changelog) in ownCloud/Release Notes/ReleaseNotes.plist
- [x] [DEV] Changelog: Created a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD
- [x] [DEV] Changelog: Moved all changelog files from the unreleased folder to the new version folder
- [x] [DEV] Inform Documentation-Team for the upcoming major/minor release with new version tag (notify #documentation-internal)
- [x] [QA] Design Test plan
- [x] [QA] Regression Test plan
- [ ] [DOC] Update https://owncloud.com/mobile-apps/#ios version numbers (notify #marketing)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [x] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)
- [x] [DEV] ownBrander: Update the ownBrander git tag in repository `customer_portal` to new release tag
- [x] [DEV] Update used Xcode version for the release in [.xcode-version](https://github.com/owncloud/ios-app/blob/master/.xcode-version)
- [x] [DEV] Inform #documentation about the new release to set new documentation branch tag

If it is required to update the iOS-SDK version:

- [ ] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code)
- [ ] [mail] inform #marketing about the new release.
- [ ] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [ ] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [x] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [ ] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [x] [DIS] Upload the binary to the App Store
- [x] [DIS] App Store Connect: Trigger release (manually)
- [x] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [x] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [x] [DIS] App Store Connect: Update changelogs
- [x] [DIS] App Store Connect: Submit for review

## BUGS & IMPROVEMENTS:
- #1344 
- #1354 
- #1358 

## QA

Regression test: https://github.com/owncloud/QA/blob/master/Mobile/iOS/Executions/Version%2012.3/Regression.md

Reports:

- [X] (1) app icon is gone in iOS 18 https://github.com/owncloud/ios-app/issues/1362#issuecomment-2348918330 [WONT FIX]
- [x] (2) Warning before first launch https://github.com/owncloud/ios-app/issues/1362#issuecomment-2352181362 [DONE]
- [x] (3) Duplicate operation fail locally https://github.com/owncloud/ios-app/issues/1362#issuecomment-2352229961 [FIXED]
- [x] (4) Bulk uploads not working https://github.com/owncloud/ios-app/issues/1362#issuecomment-2352276714 [FIXED]
- [x] (5) Downloads sometimes get stucked https://github.com/owncloud/ios-app/issues/1362#issuecomment-2352619960 [FIXED]
- [x] (6) Preview of Office files https://github.com/owncloud/ios-app/issues/1362#issuecomment-2352644027 [FIXED]
- [X] (7) Browsing through Files app https://github.com/owncloud/ios-app/issues/1362#issuecomment-2352865783  [FIXED]
- [X] (8) Files app crashing https://github.com/owncloud/ios-app/issues/1362#issuecomment-2357952311 [MITIGATED, NOT FIXED]
- [x] (9) External sharing shows different glitches and upload is not done in first instance https://github.com/owncloud/ios-app/issues/1362#issuecomment-2358217336 [FIXED]
- [X] (10) share by cloud not working in Files App https://github.com/owncloud/ios-app/issues/1362#issuecomment-2360935260 [FIXED]

**Comment by jesmrec** [comment]
### (1)

In iOS18 (latest beta-RC), app icon is not displayed after fresh install. Opening the app the icon is recovered and gone again: 

https://github.com/user-attachments/assets/07fd13ba-68c6-4bc8-9f86-7777d6678bb5

This effect does not happen in iOS 17

Tested with archived ipa, not debug.

iPhoneXR v18.0
iPad v17.6.1

**Comment by felix-schwarz** [comment]
@jesmrec That appears to be a bug in iOS 18 and nothing we can fix from our side. I guess a reboot will fix that.

**Comment by jesmrec** [comment]
### (2) (question)

in iPhoneXR, the following warning appears after a fresh install in iOS18:

![Screenshot 2024-09-03 at 14 31 45](https://github.com/user-attachments/assets/a7eb7e76-9bb3-43c4-89aa-daba935f9729)

Any affection for the app in terms of confidentially or security?

iPhoneXR v18

app `22d3551`
sdk `8ae91ff`

**Comment by jesmrec** [comment]
### (3)

1. Select any file and `Duplicate` 
2. File is created with no thumbnail
3. After some seconds -> error creating file
4. Error solved by cancelling
5. By swiping down, the file is correctly created

**Expected:**: file correctly duplicated in first instance

https://github.com/user-attachments/assets/979a89b8-d79b-48cf-bbeb-e956405b18b0

iPhone XR iOS18
iPad iPadOS17

app `22d3551`
sdk `8ae91ff`

**Comment by jesmrec** [comment]
### (4)

1. Select many files to upload (for this example, i used 200)

**Current:** media import starts and some files appear as greyed out in the list. When media import finishes, `Status` is empty but files are not in the list (just two files in the example)

**Expected:** Everything uploaded

https://github.com/user-attachments/assets/2944fff5-093a-471f-96ad-07e7800cde99

I caught some logs: 

[ownCloud_16_Sep_2024_at_10_00_18.log.txt](https://github.com/user-attachments/files/17010059/ownCloud_16_Sep_2024_at_10_00_18.log.txt)

iPhone XR iOS18
iPad iPadOS17

app `22d3551`
sdk `8ae91ff`

**Comment by jesmrec** [comment]
If this helps to simplify (4), i tried a simpler scenario in iOS18: upload a single picture to root rolder. Picture never uploads and `Status` is empty. Logs:

[ownCloud_16_Sep_2024_at_12_11_02.log.txt](https://github.com/user-attachments/files/17011380/ownCloud_16_Sep_2024_at_12_11_02.log.txt)

Permission to `Photos` is set to full access. I can provide the server i used for the test.

This scenario works fine in iPadOS17

**Comment by jesmrec** [comment]
### (5)

Downloads.

I have a folder `Test` with 5 images: `land1.jpg`, `land2.jpg`, `land3.jpg`, `land4.jpg`, `land5.jpg`

I click one by one, in order to download and preview them

2 out of 5 don't download and get stucked in `Status` with a spinner in the file list. Killing and reopening the app does not fix the problem:

https://github.com/user-attachments/assets/21e2bdc5-8ebb-4c11-bbd9-0a3466d2148d

I caught some logs, not corresponding the recording above (let me know if you need something different):

[ownCloud_16_Sep_2024_at_12_42_28.log.txt](https://github.com/user-attachments/files/17011851/ownCloud_16_Sep_2024_at_12_42_28.log.txt)

https://github.com/user-attachments/assets/21e2bdc5-8ebb-4c11-bbd9-0a3466d2148d

I was only able to reproduce in iOS18, not in iOS17

app `22d3551`
sdk `8ae91ff`

**Comment by jesmrec** [comment]
### (6)

Previewing MS Office files (docx, xlsx...)

**In iPadOS17 and stable versio**n: content is displayed and previewed

**iOS18:** 

![Screenshot 2024-09-16 at 13 20 09](https://github.com/user-attachments/assets/2f4cf749-d8c1-4996-a4b2-e96bfac71eeb)

app `22d3551`
sdk `8ae91ff`

**Comment by jesmrec** [comment]
### (7)

I get a `Content Unavailable` error when trying to browse through Files App in a oCIS account over iOS18. Not reproducible with oC10 accounts in iOS18, and working fine in iOS17.

I tried the same test with `demo.owncloud.com` and worked fine. I can provide the server in which i reproduce the error, that is a 

```
ownCloud Web UI 8.0.5
Infinite Scale 5.0.7 Community
```

**Comment by felix-schwarz** [comment]
Re (2): this message is expected when trying to connect to local servers. If a user presses "Don't allow", they will not be able to access their local server(s).

**Comment by felix-schwarz** [comment]
Re (7): As far as I can see, this is just "running out of memory". I saw it only when I had ongoing TUS uploads carried over from the app, where the allocation of even a small buffer to segment the uploaded file might make the whole File Provider trip over the limit.

I'll perform some further debugging and checks in the Simulator, however.

But since the FP is no longer used by any other parts of the app other than the FP itself, you can continue with QA on all other parts of the app.

**Comment by jesmrec** [comment]
### (8)

Operations in Files App are returning crashes. For example, removing 10 files:

https://github.com/user-attachments/assets/8182d22f-8f08-461e-beab-326358532384

File are not removed from server.

Logs:  [ownCloud_18_Sep_2024_at_11_11_23.log.txt](https://github.com/user-attachments/files/17041738/ownCloud_18_Sep_2024_at_11_11_23.log.txt)

Other basic operations like remove, duplicate or copy/paste behave the same

app: `68826f6c`
sdk: `8da653e`

**Comment by hosy** [comment]
> ### (8)
> Operations in Files App are returning crashes. For example, removing 10 files:
> 
>  ScreenRecording_09-18-2024.11-13-01_1.MP4 
> Files are not removed from server.
> 
> Logs: [ownCloud_18_Sep_2024_at_11_11_23.log.txt](https://github.com/user-attachments/files/17041738/ownCloud_18_Sep_2024_at_11_11_23.log.txt)
> 
> Other basic operations like remove, duplicate or copy/paste behave the same
> 
> app: `68826f6c` sdk: `8da653e`

Can you find a crash log or check the console while performing this task Xcode > Window > Devices > Select Device > Open Console

**Comment by jesmrec** [comment]
@hosy i saw nothing relevant, i also checked the `Window > Organizer > Crashes`, nothing from the latest day:

![Screenshot 2024-09-18 at 12 15 54](https://github.com/user-attachments/assets/f168971d-af9a-4aa3-b1ca-8ef9106d5975)

I'm testing with a released signed ipa (not debug), it may have something to do. I'll try to get something from a debug build.

**Comment by hosy** [comment]
@jesmrec on the Organizer window you can only find crash reports from TestFlight or App Store.

**Comment by jesmrec** [comment]
> @jesmrec on the Organizer window you can only find crash reports from TestFlight or App Store.

i checked, just in case. I've just checked with a debug build and i see nothing in `Xcode > Window > Devices > Select Device > Open Console` affecting the described error. Only a couple of reports but from simulator, not from real device i reproduced the problem with.

**Comment by jesmrec** [comment]
### (9)

A weird scenario, that i reproduce in both iOS17 and iOS18


1. Add account to the device (i tested with two, also valid)
2. Open the `Photos` app
3. Select some pictures or videos and share with oC

-> Folder picker is opened but accounts appear as `Connecting` forever. Both accounts are green in the app

4. In spite of the `Connecting` status, select any target folder for the file

-> `Uploading` dialog is forever in the screen. Checking the app, the file is greyed out and need to kill the app and reopen to finish the upload

https://github.com/user-attachments/assets/f2296166-4f8d-4816-af55-f90c8e999a8e

If you need logs, please ping me. I tried to get logs from the app, but the log file form that scenario weights > 600MB. 

app: `68826f6c`
sdk: `8da653e`

**Comment by felix-schwarz** [comment]
Re (8): thanks for the video & logs. The Share Extension `Info.plist` was missing the necessary keys to allow insecure `http` connections, sending the OCCore into an infinite loop of connection attempts. I added the keys with the latest commit ( https://github.com/owncloud/ios-app/pull/1385/commits/ea52e9ed2b30dc5fa556216f7c3a57b28d65f3a9 ) in #1385.

**Comment by felix-schwarz** [comment]
Re (7) and (8): I've been able to identify a few more opportunities to reduce the peak memory footprint of the File Provider further and put all of the changes it in #1387.

@jesmrec Please check if that branch fixes the issues you see.

**Comment by jesmrec** [comment]
Issue (7) is fixed. But (8) is reproducible in populated accounts.

**Comment by jesmrec** [comment]
### (10)

These are the available menus for the same item in Files App for oC10 and oCIS:
|iOS18|iPadOS17|
|-|-| 
|<img width="335" alt="Screenshot 2024-09-19 at 13 47 28" src="https://github.com/user-attachments/assets/3218205b-9bae-4fed-a410-997b563c5fe4">|<img width="390" alt="Screenshot 2024-09-19 at 13 48 06" src="https://github.com/user-attachments/assets/20a20077-ec18-4a5c-9352-e56633ae63ff">|

Many options are missing.

app `e0478794`
sdk `87c68c0`

iPhone XR v18.0
iPad 10th gen v17.6

**Comment by hosy** [comment]
@jesmrec regarding (10):

Just had a look and it es available for me. Tested on demo.owncloud.com:

![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2024-09-19 at 14 41 55](https://github.com/user-attachments/assets/dca6783a-9fc3-4a5c-9d57-766e18305b89)

**Comment by jesmrec** [comment]
i rechecked with same devices and versions and now it is available... pretty weird. I will take another look, just in case i find any reason. Thanks for checking @hosy

**Comment by jesmrec** [comment]
About the  `share by cloud`: if server is not secured (https with self signed or similar), the sharing is not opened. Something similar happened in the previous reports that @felix-schwarz fixed. Looks like that:

https://github.com/user-attachments/assets/cc4ca3da-3d81-4824-8b68-e9ab139ae50d

Something fixable? should go to 12.3.1? what do you mean?

**Comment by felix-schwarz** [comment]
Re (10): @jesmrec Like for the share extension, I added a `NSAppTransportSecurity` section to the `Info.plist` in https://github.com/owncloud/ios-app/pull/1385/commits/e196e02cb44b4c25d9f2326f55c3e66816535df4 (release/12.3.0) to allow plain HTTP connections. Please check if that fixes it.

**Comment by jesmrec** [comment]
@felix-schwarz with the following:

app `e196e02`
sdk `b955bce`

unfortunately i still reproduce [this](https://github.com/owncloud/ios-app/issues/1362#issuecomment-2360935260). If some extra info is required, let me know.

**Comment by hosy** [comment]
@jesmrec I´ve added the `NSAppTransportSecurity ` to two missing targets. Please have a look again with the commit `5ed2b9f38196e012c38126a3c56b6341220540ca`. File Provider UI target was missing for your finding.

**Comment by jesmrec** [comment]
@hosy, fixed with your commit!

**Comment by jesmrec** [comment]
Release `12.3.0` is approved on my side.

**Xcode version**: `16.0 (16A242d)`

**Approved commits**:

- app:  `5ed2b9f`
- sdk: `b955bce`

**Devices:**

- iPhone XR - iOS 18.0
- iPad 10th gen - iPadOS 17.6.1

**QA:**

- [Regression test](https://github.com/owncloud/QA/blob/master/Mobile/iOS/Executions/Version%2012.3/Regression.md)
- [E2E tests report vs oCIS stable](https://reports.cucumber.io/reports/4b15ca42-3d77-43b8-89ed-91374c9d7f7f)

Reports in QA-phase in the top message

**Known issues and regards:**

- In the iPhone XR with iOS 18, the app icon is not always displayed in the device list of apps, as reported [here](https://github.com/owncloud/ios-app/issues/1362#issuecomment-2348918330). As [stated by dev team](https://github.com/owncloud/ios-app/issues/1362#issuecomment-2349003395), this is probably an iOS bug.

- Shortcuts feature (IAP) is not available

- Files provider (Files App): there are known memory issues that caused problems with crashes like [this one](https://github.com/owncloud/ios-app/issues/1362#issuecomment-2357952311). Some work was done to mitigate them, but the issues are not completely gone and need deeper research to be fixed. They are likely reproducible in populated accounts. 

- Bulk uploads worked fine till ~400 files. A higher number uses to lead to errors, probably because the known memory issues.
