### ISSUE TITLE
iOS 18 (beta) - Xcode 16 (beta)

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#1371]
This issue is aimed to report and fix problems with the new incoming versions, which testing will be done shortly

- [x] (1) Xcode returns error in building time https://github.com/owncloud/ios-app/issues/1371#issuecomment-2249782857 [FIXED]
- [x] (2) Problem in uploads https://github.com/owncloud/ios-app/issues/1372#issue-2434555412 [FIXED in feature/reduce-mem-footprint]
- [X] (3) Scan uploads not working https://github.com/owncloud/ios-app/issues/1371#issuecomment-2326386420 [NOT REPRODUCIBLE]
- [x] (4) Warning in fresh install https://github.com/owncloud/ios-app/issues/1371#issuecomment-2326409812
- [X] (5) Files App, difficult to browse https://github.com/owncloud/ios-app/issues/1371#issuecomment-2328158782 [FIXED]
- [x] (6) `Loading` spinner forever in empty folders in Files App https://github.com/owncloud/ios-app/issues/1371#issuecomment-2330973610

**Comment by jesmrec** [comment]
### (1)

Xcode 16.0 beta 3 (16A5202i)

Building the app (`master ffb28aa8`), an error happens and process exit:


![Screenshot 2024-07-25 at 10 35 45](https://github.com/user-attachments/assets/6f59116c-9d56-4e97-9a8f-e75b937806ba)

no matter the target (real device or simulator), error is always there.

**Comment by jesmrec** [comment]
### (2)

https://github.com/owncloud/ios-app/issues/1372#issue-2434555412

**Comment by jesmrec** [comment]
### (3)

https://github.com/owncloud/ios-app/issues/1372#issuecomment-2264978472

**Comment by jesmrec** [comment]
> ### (3)
> [#1372 (comment)](https://github.com/owncloud/ios-app/issues/1372#issuecomment-2264978472)

not reproducible

**Comment by jesmrec** [comment]
### (4)

in iPhoneXR, the following warning appears after a fresh install in iOS18:

![Screenshot 2024-09-03 at 14 31 45](https://github.com/user-attachments/assets/a7eb7e76-9bb3-43c4-89aa-daba935f9729)

Any affection for the app in terms of confidentially or security?

**Comment by jesmrec** [comment]
### (5)

Files App not loading content:

https://github.com/user-attachments/assets/acfb6245-5a14-4612-bef9-33b2420f9755

I caught some logs:

[ownCloud_3_Sep_2024_at_14_39_02.log.txt](https://github.com/user-attachments/files/16848799/ownCloud_3_Sep_2024_at_14_39_02.log.txt)

iPhoneXR v18-beta`
`v12.2.1´ (current stable)

**Comment by jesmrec** [comment]
### (5)

Files App: while browsing, `Content Unavailable` messages are displayed steadily, and folders are sometimes loading forever. 

Here, a video and logs:

https://github.com/user-attachments/assets/be0e59c4-70a4-466a-b067-c6d0f31017ed

[ownCloud_4_Sep_2024_at_09_45_18.log.txt](https://github.com/user-attachments/files/16862606/ownCloud_4_Sep_2024_at_09_45_18.log.txt)

iPhone XR v18-beta
`v12.2.1`

**Comment by jesmrec** [comment]
### (6)

Current: In Files App navigation to empty folders shows and infinite loop `Loading`

Expected: Placeholder `Folder is Empty`

iPhone XR 
v18-beta
`74be5b55`
