### ISSUE TITLE
App Settings

### ISSUE THREAD

**Issue by nasli** [owncloud/ios-app#3]
As an _user_ I want be able to change some settings of the app _so_ I can customize some features

To discuss, if settings are going to be per account or common to the app, or only some common

- [x] Create skeleton (view)
- [x] Settings sections:
  - Per app:
     - [x] Security: Passcode/TouchId/FaceId/ [WIP]

            - Time slot until next time to request passcode/touch id/ face id

     - [x] Instant uploads: 

            - Photos: By enabling, all pics taken from camera will be queued in uploads queue, if the app is alive, or when the app is opened

            - Videos: By enabling, all video taken from camera will be queued in uploads queue, if the app is alive, or when the app is opened. https://github.com/owncloud/ios-app/issues/3#issuecomment-373005114

            - Background: the posibility of automatic upload when app is in background. A big change in location triggers the upload.

            - Wifi only: If it is enabled, stuff will be uploaded under wifi. Othercase, the stuff will be queued. When wifi is recovered, content will be uploaded. Same option for both pics and videos.

            - Account to upload: with only one account, this one is the selected. If there are more than one, user select one of the available. In case of deletion of the selected account, instant uploads will disable.

           - Target folder:  Folder into the selected account to upload instantly. Default: /InstalUploads. In case of removal, create again. 

           - Size: Size filter to upload content greater than. 

     - [X] More: Help, recommend to a Friend, Send Feedback, Imprint
  - Per account:
     - [x] Clear cache

- [X] Include version of the app and commit hash -> https://github.com/owncloud/ios-app/issues/51

- [X] Update Figma Design, get screenshot here

This is an epic, smaller issues will be created to develop in an incremental way

**Comment by nasli** [comment]
Updated settings sections, pending define design

**Comment by jesmrec** [comment]
It would be nice to have the possibility to select the target folder in which the content is uploaded

**Comment by jesmrec** [comment]
would it be interesting for the first iteration to set a filter to max size of video to upload. For example, for videos greater than 100MB (for instance), not to upload instantly.

@michaelstingl

**Comment by SamuAlfageme** [comment]
I'd say some of these settings should be moved to different issues as they're fundamental part of features. 

Since @pablocarmu was looking into different apps using lock methods - I'll explain 3 personal picks: 

| App            | Lock Screen | Settings | Details |
|----------------|-------------|----------|---------|
| [Bitwarden](https://itunes.apple.com/us/app/bitwarden-password-manager/id1137397744)      |![photo_2018-04-30_10-17-59](https://user-images.githubusercontent.com/2644445/39419348-c5c33574-4c5f-11e8-9e2f-068e4c4affc0.jpg)|![photo_2018-04-30_10-12-30](https://user-images.githubusercontent.com/2644445/39419207-18051876-4c5f-11e8-89ea-1978f326c81b.jpg)| <ul><li>Lock Options</li><ul><li>Immediately</li><li>1 min</li><li>15 min</li><li>...</li></ul><li>Choose one: PIN or Touch ID</li><li>Manual lock inside app</li></ul> |
| [Standard Notes](https://itunes.apple.com/us/app/standard-notes/id1285392450) |![photo_2018-04-30_10-12-50](https://user-images.githubusercontent.com/2644445/39419204-17d0e3bc-4c5f-11e8-83a9-c62b7b060be6.jpg)|![photo_2018-04-30_10-12-45](https://user-images.githubusercontent.com/2644445/39419205-17ea77fa-4c5f-11e8-9b01-f496b299da69.jpg)| <ul><li>Lock Options</li><ul><li>Immediately</li><li>On Quit</li></ul><li>Passcode (can be alphanumeric/PIN) and Touch ID can be</li><ul> <li>Enabled separately</li><li>Required together</li></ul></ul> |
| [Authy](https://itunes.apple.com/es/app/authy/id494168017) | ![photo_2018-04-30_10-12-50 2](https://user-images.githubusercontent.com/2644445/39419203-17b77ec2-4c5f-11e8-8370-e6dd341ca883.jpg) |![photo_2018-04-30_10-12-52](https://user-images.githubusercontent.com/2644445/39419201-17931fb4-4c5f-11e8-8836-df77e9658690.jpg)|<ul><li>Touch ID can only be enabled together with PIN and used alternatively</li><li>"Protect Entire App": require on start</li></ul> |

**Comment by michaelstingl** [comment]
we can start with 4-digit. maybe we will need more in the future… (migration?)

**Comment by javiergonzper** [comment]
Yes, if in the future we need more than 4 digits we can modify the UI an allow to our users use 4 digits, 6, alphabetical... whatever 👍.
I will do 4 digits then

**Comment by michaelstingl** [comment]
Could we display the Git hash somewhere on the settings screen?

![2018-05-13_21_36_48](https://user-images.githubusercontent.com/214010/39971124-85d48be2-56f6-11e8-82d4-7bfe273d051d.png)

**Comment by hosy** [comment]
Last missing features are implemented since version 1.1.0
