### ISSUE TITLE
[Release] 1.0.1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#368]
Release a new version
## TASKS:

Git & Code

- [x] [GIT] Create branch `release/1.0.1` (freeze the code) @jesmrec 
- [X] [DEV] Update version number `version_1.0.1`
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md) https://github.com/owncloud/ios-app/pull/407
- [x] [TRFX] Update translations from transifex branch.
- [x] [QA] Design Test plan: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version_1.0.1.md @jesmrec 
- [x] [QA] Regression Test plan @jesmrec 
- [ ] [DOC] Update user manual with the new functionalities https://github.com/owncloud/ios-app/pull/398
- [ ] [DOC] Update owncloud.org/download version numbers (notify rocketchat #marketing)
- [x] [DEV] Settings: Check Help URL
- [ ] [DEV] Settings: Feedback subject line: `$version ownCloud iOS app feedback` or something… (ticket system often crops the end of the subject line)
- [x] [DEV] Settings: Check Recommend URL

App Store 

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [x] [DIS] App Store Connect: Update screenshots if needed
  - [x] Empty accounts (`Welcome`) `[10_ios_accounts_welcome_demo.png]`
  - [x] Multiple accounts `[11_ios_accounts_list_demo.png]`
  - [x] File Listing `/Photos/*` `[20_ios_files_list_demo.png]`
  - [x] File Actions `/Photos` `[21_ios_files_actions_demo.png]`
  - [x] PDF preview `/ownCloud Manual.pdf` (Page 13) `[22_ios_files_preview_pdf_demo.png]`
  - [x] Quick Access `[40_ios_quick_access_demo.png]`
  - [x] Settings (Passcode enabled) `[60_ios_settings_demo.png]`
  - [x] give up-to-date screenshot of the sharing and settings screens to @lefherz 
- [x] [DIS] Upload the binary to the App Store
- [x] [DIS] App Store Connect: When release (manually, automatically, automatically not early than date)
- [x] [DIS] App Store Connect: How to release (immediately to all the users o 7-day period phased release)
- [x] [DIS] App Store Connect: Reset iOS Summary Rating (Keep existing or reset the rating)
- [x] [DIS] App Store Connect: Update changelogs
- [x] [DIS] App Store Connect: Submit for review

If it is required to update third party:

- [x] [DIS] Update THIRD_PARTY.txt

If it is required to update the iOS-SDK version:

- [x] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code) 
- [x] [mail] inform john@owncloud.com and emil@owncloud.com about the new release.
- [x] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [x] [GIT] Merge branch `release/1.0.0` in `master`
- [x] [GIT] Create tag and sign it `1.0.0`
- [x] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

Git

- [x] [GIT] Merge branch `release/1.0.1` in master
- [x] [GIT] Create tag and sign it `version_1.0.1`
- [x] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

## Regression test

https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version_1.0.1.md
