### ISSUE TITLE
[RELEASE] 1.1.0

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#461]
Release a new version
### Git & Code

- [x] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [x] [TRFX] Update translations from transifex branch.
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [QA] Design Test plan
- [x] [QA] Regression Test plan
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [x] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

If it is required to update the iOS-SDK version:

- [ ] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code) 
- [x] [mail] inform #marketing about the new release.
- [x] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [x] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [x] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [x] [DIS] Upload the binary to the App Store
- [x] [DIS] App Store Connect: Trigger release (manually)
- [x] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [x] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [x] [DIS] App Store Connect: Update changelogs
- [x] [DIS] App Store Connect: Submit for review

## BUGS & IMPROVEMENTS:

Test Plan:

https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%201.1.0/Version_1.1.0.md

- [X] (1) Non openable files https://github.com/owncloud/ios-app/issues/461#issuecomment-529871705 [FIXED]
- [X] (2) Open downloaded PDFs does not show the options https://github.com/owncloud/ios-app/issues/461#issuecomment-529875429 [FIXED]
- [X] (3) Download cut https://github.com/owncloud/ios-app/issues/461#issuecomment-529902624 [FIXED]
- [X] (4) Folder av. offline errors while downloading https://github.com/owncloud/ios-app/issues/461#issuecomment-529914450  [FIXED]
- [X] (5) https://github.com/owncloud/ios-app/issues/501 [FIXED]
- [x] (6) Waring of non-imported media after taking instant uploads https://github.com/owncloud/ios-app/issues/461#issuecomment-530783347 [FIXED]
- [X] (7) wording improvement in i.u. https://github.com/owncloud/ios-app/issues/461#issuecomment-530788007
- [X] (8) stucked after selecting many files https://github.com/owncloud/ios-app/issues/461#issuecomment-530800672 [WONT FIX HERE]
- [x] (9) stucked upload (not always reproducible)  https://github.com/owncloud/ios-app/issues/461#issuecomment-530807466 [FIXED]
- [X] (10) Downloaded file moved into av. offline folder is not av. offline https://github.com/owncloud/ios-app/issues/461#issuecomment-531128747 [FIXED]

**Comment by jesmrec** [comment]
### (1)

1. Tap on a non-openable file (f.ex. a zip file)

Current: file is not downloaded, and no information is shwn
Expected: In 1.0.4, file was downloaded. Then the icon, size and date were shown in preview mode.

**Comment by jesmrec** [comment]
### (2)

1. Download a PDF file (correct preview)
2. Go back to the list of files
3. Open again the downloaded pdf

Current: options to "Go to" , "List" and "Search" are not there
Expected: In 1.0.4, these options were available.

**Comment by jesmrec** [comment]
### (3)

1. Download a big file (f. ex, a video)

Current: Preview is shown with the progress bar. If you go back, the download is cancelled. So, it is not posible to download several at time:

![Sep-10-2019 13-59-07](https://user-images.githubusercontent.com/14894746/64612083-3ad35780-d3d3-11e9-8ff6-5a9e1193217c.gif)

Expected: In 1.0.4, file started to download in the files view itself

![Sep-10-2019 14-00-45](https://user-images.githubusercontent.com/14894746/64612174-73733100-d3d3-11e9-9833-1c788ea4c470.gif)

**Comment by jesmrec** [comment]
### (4)

In a just created bookmark, I have a folder called `images` in the root, and some images inside (~30). 

1. Set the folder as av. offline

Current: i get errors while downloading like this one:

![Screenshot 2019-09-10 at 14 33 08](https://user-images.githubusercontent.com/14894746/64614170-32315000-d3d8-11e9-89cf-d135f941d297.png)

I got a debug log:

[ownCloud_10_Sep_2019_at_14_32_49.log.txt](https://github.com/owncloud/ios-app/files/3595614/ownCloud_10_Sep_2019_at_14_32_49.log.txt)

Expected: everything av offline inside the folder with no errors

**Comment by mneuwert** [comment]
@jesmrec  I could have reproduce it with following steps:
- Prepare folder with pictures
- Make folder available offline -> OK
- Make folder unavailable offline -> OK
- Make available offline once again -> Failing to download

What I found so far, it seems to happen due to checksum verification failure _OCSyncActionDownload.m:254_ is then the` if` branch which is taken. Which then leads to setting internal error as the download itself was OK. Tried to debug but brought Xcode to crashing in the end cc: @felix-schwarz

**Comment by felix-schwarz** [comment]
As of `1d99edd`, issue #4 should be fixed. @mneuwert @jesmrec

**Comment by jesmrec** [comment]
About (4): with commits `1d99edd` (app) `3e22bcf` (sdk), problem is still reproducible. Attached logs, the file within the alert error is `land1.jpg`

[ownCloud_11_Sep_2019_at_12_31_29.log.txt](https://github.com/owncloud/ios-app/files/3600289/ownCloud_11_Sep_2019_at_12_31_29.log.txt)

**Comment by mneuwert** [comment]
@felix-schwarz I can also reproduce (4), still sometimes `OCEvent.file` property is `nil` in `[OCSyncActionDownload handleResultWithContext:]`

**Comment by felix-schwarz** [comment]
@jesmrec @mneuwert Thanks for the feedback. That was likely caused by a serialization error. Should work now. Please keep an eye on errors in the log (searching for `[ERRO]`) when testing. This one was:
```
2019-09-10 14:33:10.414000+0200 ownCloud[734:090909] [ERRO] | Error decoding object from data: Error Domain=NSCocoaErrorDomain Code=4864 "value for key 'NS.objects' was of unexpected class 'OCSyncIssue'. Allowed classes are '{(
    NSDictionary
)}'." UserInfo={NSDebugDescription=value for key 'NS.objects' was of unexpected class 'OCSyncIssue'. Allowed classes are '{(
    NSDictionary
)}'.} [OCKeyValueRecord.m:92|FULL]
```
in the first log, and a similar one in the second.

**Comment by felix-schwarz** [comment]
@jesmrec @mneuwert Totally forgot: should be fixed now. Please do a quick search for `[ERRO]` in the logs even in case of no issues, though. Not all errors become immediately visible for users, but are typically reported in the logs.

**Comment by jesmrec** [comment]
unfortunately, with commits 

Host: com.owncloud.ios-app 1.1.0 (140) #4ac37bc; SDK: 1.0 (1) #de3a361;

still happens. New log attached

[ownCloud_11_Sep_2019_at_15_27_50.log.txt](https://github.com/owncloud/ios-app/files/3601006/ownCloud_11_Sep_2019_at_15_27_50.log.txt)

**Comment by mneuwert** [comment]
@felix-schwarz still, please can you confirm that serializing of `OCEvent.file` property is not required? Is it done on purpose?

**Comment by felix-schwarz** [comment]
> @felix-schwarz still, please can you confirm that serializing of `OCEvent.file` property is not required? Is it done on purpose?

Thanks. I somehow managed to misread your original post. Sorry! The `file` property was indeed missing in serialization/deserialization. Fixed that.

@jesmrec @mneuwert Please retry with the latest commit. Should be fixed now.

**Comment by mneuwert** [comment]
@felix-schwarz I did a clean re-test with the app installed from scratch and I don't see the issue anymore. cc: @jesmrec

**Comment by jesmrec** [comment]
(4) is fixed now

**Comment by jesmrec** [comment]
> @jesmrec hm.. regarding instant photo upload.. yes, right.. app won't upload anything until you open it. I just wanted to say, that warning is applicable for both manual and automatic photo upload.

afaik, the warning is displayed because non-imported pics are not uploaded. But if you take pics just after an installation and enabling the feature, there are no pending pics to import from photo library (no uploads before). i'm missing any detail.

**Comment by jesmrec** [comment]
### (10)

1. Set a folder as av. offline

Move a non-downloaded file inside the av. offline folder -> the file is now downloaded av. offline
Move a downloaded file inside the av. offline folder -> the file is not av. offline

The previous status of the file should not affect to its available offline condition.

**Comment by felix-schwarz** [comment]
@jesmrec Good catch! As of cb393de, finding (10) should be fixed (the commit message has a typo and says 11, but I meant to write 10 🤷‍♂️).

**Comment by jesmrec** [comment]
(10) is fixed

**Comment by mneuwert** [comment]
@jesmrec Ok, I understood what (6) actually is... it is kind of race condition and the message can be shown if upload task is currently running. Will come back with the fix

**Comment by jesmrec** [comment]
(6) -> fixed

(8) -> will open a separate issue, since it is not a regression 

(9) -> not reproducible anymore. But, we should be aware if it is reproducible again.

**Comment by jesmrec** [comment]
finally, I performed an upgrade test from 1.0.4 to 1.1.0 with successful result.

From my side, we can move forward the release, without forgetting the (9) report, just in case.

**Comment by jesmrec** [comment]
(9) is out there, it seems to. Will try to get more logs.

**Comment by jesmrec** [comment]
After latests fixes, was not able to get more stucked uploads. 

Upgrading from 1.0.4 was also correct (over iOS12)

Performed basic checks over iOS13.1 and iPadOS13, since this is out there:

- [X] Basic auth
- [X] OAuth2
- [X] Transfers (uploads & downloads)
- [X] Basic operations (create folder, move, copy, delete, rename, duplicate. open in)
- [X] Av. offline (files and folders with subfolders)
- [X] Multiaccount
- [X] Previews and Gallery
- [X] Files App (basic operations)

Deeper iOS13 testing will be done in the scope of https://github.com/owncloud/ios-app/issues/502, by building the app with the new XCode version, together with the new improvements inside version of the app 1.2

**Comment by hosy** [comment]
@settermjd today we've uploaded version 1.1 to Apple for review. We have also some new functionalities which needs to be documented in the manual. Please can you take care?
If you need help or screenshots, please contact me.

**Comment by michaelstingl** [comment]
> We have also some new functionalities which needs to be documented in the manual.

@hosy Open new issue in the docs repo with a list of the new stuff? Please also mention me in the new docs repo.
