### ISSUE TITLE
[iOS13] Regression

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#502]
Testing the app on iOS13

https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%201.1.0/iOS13.md

Bugs & improvements:

- [x] (1) Sharing searching bar style https://github.com/owncloud/ios-app/issues/502#issuecomment-531183212 [FIXED]
- [X] (2) white line https://github.com/owncloud/ios-app/issues/502#issuecomment-531185042 [NR]
- [x] (3) renaming folder inside files app with existing name https://github.com/owncloud/ios-app/issues/502#issuecomment-531291240 [FIXED]
- [x] (4) Sorting options https://github.com/owncloud/ios-app/issues/502#issuecomment-535483745 [FIXED]
- [x] (5) Settings upper side of the screen in classic theme https://github.com/owncloud/ios-app/issues/502#issuecomment-535484416 [FIXED]
- [x] (6) Spinner in file list https://github.com/owncloud/ios-app/issues/502#issuecomment-535488488 [FIXED]
- [x] (7) Multiselection circles are not barely visible in dark mode https://github.com/owncloud/ios-app/issues/502#issuecomment-535493842
- [x] (8) Misplaced breadcrumbs https://github.com/owncloud/ios-app/issues/502#issuecomment-538302607 [FIXED]

**Comment by jesmrec** [comment]
### (1)

 Sharee searching bar letters are black over black in dark and classic themes. Every typed character makes the lupe blinking and the cursor moves left and right

**Comment by jesmrec** [comment]
### (2)

In classic mode, browse inside a folder (not reproducible in root). A white bar appears just below the searching bar

<img width="395" alt="Screenshot 2019-09-13 at 12 21 23" src="https://user-images.githubusercontent.com/14894746/64855931-369c7980-d621-11e9-96d9-f4889f336fe3.png">

**Comment by jesmrec** [comment]
### (3)

1. Open Files app
2. Rename a folder inside and oC app, setting an existig name

Current: files app crashes
Expected: error message

**Comment by jesmrec** [comment]
From this point, tests done over 1.1 version of the app (`1e1f5da`), built with XCode11.1 and running onto iOS13.1

**Comment by jesmrec** [comment]
### (4) 

Sorting options:

In portrait, the options are slightly misplaced:

![Screenshot 2019-09-26 at 14 38 08](https://user-images.githubusercontent.com/14894746/65688365-4e392080-e06b-11e9-8829-2b859f2618d5.png)

In landscape, with Classic and Dark modes, the options with dark background color are not readable (in real device more difficult as in the screenshot here):

![Screenshot 2019-09-26 at 14 39 45](https://user-images.githubusercontent.com/14894746/65688509-8fc9cb80-e06b-11e9-9b11-37c3ed46bf64.png)

**Comment by jesmrec** [comment]
### (5)

With Classic Theme, the Settings view shows different color in upper side:

![Screenshot 2019-09-26 at 14 42 15](https://user-images.githubusercontent.com/14894746/65688696-d9b2b180-e06b-11e9-969f-f2b376e69408.png)

**Comment by jesmrec** [comment]
### (6)

With dark theme: in list of files by pulling down the spinner is too dark and not visible

**Comment by jesmrec** [comment]
### (7)

Probably related with some of the issues above, in dark theme, the multiselection circles at the left on the screen are not visible with the color scheme

**Comment by hosy** [comment]
> ### (7)
> Probably related with some of the issues above, in dark theme, the multiselection circles at the left on the screen are not visible with the color scheme

@jesmrec the color of the multi selection circles cannot be changed without an ugly hack.

**Comment by hosy** [comment]
@jesmrec please re-check all UI related issues with the latest dark mode PR commit.

**Comment by jesmrec** [comment]
### (8)

1. Browse inside the folder structure
2. Tap in the chevron for breadcrumbs

Current: Rows are misplaced:

![Screenshot 2019-10-04 at 10 31 06](https://user-images.githubusercontent.com/14894746/66193085-2280f080-e692-11e9-8aa2-594e2715b65f.png)

**Comment by hosy** [comment]
@jesmrec (8) is fixed

**Comment by felix-schwarz** [comment]
> ### (7) [WONT FIX]
> Probably related with some of the issues above, in dark theme, the multiselection circles at the left on the screen are not visible with the color scheme

Fixed in `feature/darkmode`.

**Comment by felix-schwarz** [comment]
> ### (3)
> 1. Open Files app
> 2. Rename a folder inside setting an existig name
> 
> Current: files app crashes
> Expected: error message

Couldn't reproduce that. On iOS 10.3.2, the Files app told me that "communication with a helper app failed" when in reality, the File Provider is still running and returned a correct error ("Item already exists").

Will see if rewriting the returned error can work around what looks like a bug in error reporting in Files app.

**Comment by felix-schwarz** [comment]
Follow-up: discovered this in the logs:
```
2019-10-07 11:16:24.787000+0200 ownCloud File Provider[782:062307] 🔵 | [OS] [default] [CRIT] Provider returned error from domain OCError which is unsupported. Supported error domains are NSCocoaErrorDomain, NSFileProviderErrorDomain. [NSLog:0|FULL]
2019-10-07 11:16:24.788000+0200 ownCloud File Provider[782:062307] 🔵 | [OS] [default] [ERROR] Unsupported error was Error Domain=OCError Code=33 "Couldn't rename Photos to Documents, because another item with that name already exists. (error 33)" UserInfo={NSLocalizedDescription=Couldn't rename Photos to Documents, because another item with that name already exists.} [NSLog:0|FULL]
```
That's new and likely results to that confusing message in the UI. What a bummer! Will need to check how to best work with that limitation - and if custom error messages are still possible at all.

**Comment by felix-schwarz** [comment]
Just pushed the fix for finding 3 to `feature/darkmode` (to simplify testing). @jesmrec

**Comment by jesmrec** [comment]
(3) fixed

**Comment by jesmrec** [comment]
Everything fixed in terms of regression. So, closing. New bugs/features will be faced in specific issues.
