### ISSUE TITLE
Files: Favorites

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/ios-app#52]
_This is a continuation of https://github.com/owncloud/ios/issues/652 and https://github.com/owncloud/core/issues/24671_ 

As I see it, there's these 3 sides of the picture: 

- [ ] Display an indication on the files list for favorites based on `oc:favorite` - https://github.com/owncloud/ios-sdk/issues/15
- [ ] Mark/Unmark a file as favorite - see `PROPPATCH` syntax on https://github.com/owncloud/core/issues/31438
- [ ] List all the favorites for the user: https://github.com/owncloud/ios-sdk/issues/14 

cc/ @michaelstingl for mockups or user-interaction design

**Comment by hosy** [comment]
All these feature requests are implemented since version 1.0.0
