### ISSUE TITLE
[RELEASE] 1.2

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#550]
### Git & Code

- [x] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [x] [TRFX] Update translations from transifex branch.
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [QA] Design Test plan
- [x] [QA] Regression Test plan
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

If it is required to update the iOS-SDK version:

- [x] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code) 
- [ ] [mail] inform #marketing about the new release.
- [ ] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [ ] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [x] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [x] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [x] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [x] [DIS] Upload the binary to the App Store
- [x] [DIS] App Store Connect: Trigger release (manually)
- [x] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [x] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [x] [DIS] App Store Connect: Update changelogs
- [x] [DIS] App Store Connect: Submit for review

## QA

Regression test plan:

https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%201.2.0/Regression.md

## BUGS & IMPROVEMENTS:

- [X] (1) Share sheet lost https://github.com/owncloud/ios-app/issues/550#issuecomment-549715346  [FIXED]
- [x] (2) Rename not posible https://github.com/owncloud/ios-app/issues/550#issuecomment-561056538 [iOS bug]
- [x] (3) https://github.com/owncloud/ios-app/issues/568 [FIXED]
- [X] (4) AudioPlayer Playback https://github.com/owncloud/ios-app/issues/550#issuecomment-563969431 [FIXED]
- [X] (5) Audio Player Controls https://github.com/owncloud/ios-app/issues/550#issuecomment-563969548 [FIXED]
- [x] (6) Save from .doc with no connection https://github.com/owncloud/ios-app/pull/574#issuecomment-564130764 [FIXED]
- [X] (7) Instant uploads for videos in mp4 are broken https://github.com/owncloud/ios-app/issues/550#issuecomment-564456541 [SOLVED]
- [X] (8) Files App folder duplication https://github.com/owncloud/ios-app/issues/550#issuecomment-564486402 [FIXED 13.3]
- [X] (9) Uploads in background https://github.com/owncloud/ios-app/issues/550#issuecomment-564516422 [WONT FIX]
- [X] (10) Video streaming in multiwindow https://github.com/owncloud/ios-app/issues/550#issuecomment-564619019 [WONT FIX, iOS bug]
- [X] (11) Credentials revoked while uploading https://github.com/owncloud/ios-app/issues/550#issuecomment-565382903 [WONT FIX HERE, new issue]
- [X] (12) Glitch in status view https://github.com/owncloud/ios-app/issues/550#issuecomment-565857183  [WONT FIX HERE, new issue]
- [x] (13) upgrade iOS13.2 -> 13.3, media import not working https://github.com/owncloud/ios-app/issues/550#issuecomment-566924112

**Comment by jesmrec** [comment]
### (1)

Share sheet is lost

1. Open Files app
2. Select an item, and "Share"
3. Select ownCloud

Current: Share sheet is not displayed
Expected: Share sheet displayed

**Comment by jesmrec** [comment]
### (2)

1. Open an account
2. Rename an item

Current: Not posible. 
Expected: posible

iOS 13.2

**Comment by jesmrec** [comment]
### (3)

Share sheet in iPad: https://github.com/owncloud/ios-app/issues/568

**Comment by hosy** [comment]
## (4) AudioPlayer Playback
- Select an audio file and start playing
- put app into the background
- stop audio playback from lock screen
- switch back to app and go back to file list view
- switch to iOS lock screen
- start audio playback from control center (last selected audio file from OC app does appear)

### Result:
- Audio playback immediately stops

### Expected:
- Audio file starts playing
OR
- remove audio file from iOS control, if it is not possible

**Comment by hosy** [comment]
## (5) Audio Player Controls
If there is a list of media files in a folder the app plays this files in a row, also if app is in the background.
In the iOS audio control center it is not possible to select next or previous media file.

### Expected:
From the iOS media controls it should be possible to select next or previous item, if there are more than one available in a folder

**Comment by mneuwert** [comment]
## Re: (5) Audio Player Controls
@hosy So, looks like you can't have both: skip X seconds AND playing next track. At least if skip is enabled, play next / previous track controls are not visible but I didn't test with headphones / CarPlay how it would behave if I trigger next / previous commands using external hardware.

Actually I loved skipping 10s back and forth since I was testing with mp3 files from my Japanese course but for music it is probably less useful.

**Comment by jesmrec** [comment]
### (7)

1. Install the app from scratch and add a bookmark.
2. In Settings, enable "Instant Upload Videos" (selecting a path to upload) and "Convert videos to mp4"
3. Take videos with the camera

Current: Videos are not uploaded. If you disable the toggle "Convert videos to mp4" and take more videos, everything is uploaded in mov format
Expected: If the "Convert videos to mp4" is enabled, videos are upload in mp4 instantly (after reopening app)

iPhoneX v13.2, iPadPro 13,2
oC 10.3.1

**Comment by jesmrec** [comment]
### (8) 

1. In Files App, duplicate a folder (non-empty)

Current: Takes a long time and appears shadowed forever.
Expected: Duplicated correctly

iPhoneX 13.2
oC 10.3.1

**Comment by mneuwert** [comment]
### Re: (4) 
Have a fix for it, would commit together with fix for (5).

**Comment by jesmrec** [comment]
### (9)

Check these steps out:

1. "Upload file from your photo library"
2. Select an album with many pics. I took one with 200 pics
3. Select all and upload
4. Open "Status" tab to check the "Media Import" on the top. Wait till everything is imported (at this point, uploads are already running, but most of them are still pending)
5. Minimize the app or switch to another app

Current: Uploads keep running ~1 minute and then stops. They resumed when the app goes to foreground again

Expected: Since everything was already imported, uploads don't stop and keep running in background.

is this scenario the expected one?

iPhoneX v13.2
oC 10.3.1
commit `bafc8469`

**Comment by hosy** [comment]
@jesmrec (1) is fixed and needs new QA

### Tests:
- on iPadOS 13: with one window open
- on iPadOS 13: with more than one window open
- on iPadOS 12
- on iOS 13
- on iOS 12

I thought on iOS 13 we can import more than one file, but this is not working. Like on iOS 12 only one file can be imported at once.

**Comment by jesmrec** [comment]
About (4) and (5):

(4): the chosen fix removes the music controls from the lock screen, is this correct @mneuwert ?

(5): Tapping in the pause button, the music stops but the song. I mean:

1. Play the music
2. Go to iOS lock screen
3. Tap on pause (f. ex, song is paused in 1:00)
4. Wait 20 seconds and tap on Play to resume

Current: Song is resumed in 1:20
Expected: Song is resumed in 1:00, where it was paused.

![Dec-11-2019 15-55-07](https://user-images.githubusercontent.com/14894746/70632197-a88b5b80-1c2e-11ea-9ff9-df7d0792bced.gif)


When you tap on Pause (step 3), the progress indicator moves to 0:00. This does not happen always... a bit weird.

**Comment by jesmrec** [comment]
About (1):

Sharing from Files App: in iOS13.2.2 (iPhoneX), it works OK if the file is already downloaded in Files App. You can share it with oC, selecting an account and then, a target folder. But, if the file is not downloaded in Files App (cloud icon on the right), the file is not downloaded after selecting oC as app to share with:

![Dec-11-2019 16-16-22](https://user-images.githubusercontent.com/14894746/70633955-aecf0700-1c31-11ea-91a1-976fbd445bb3.gif)

It is noticeable that iPadOS13.2.2 does not reproduce this issue. It works fine. With iOS12 (iPhone and iPad), correct behaviour.

It was tested in all devices, checking:

- Files downloaded and non-downloaded to share
- Portrait and landscape orientation (specially in iPads)
- Saving in root and non-root
- Saving in different accounts (multiaccount)
- Using multi-window (iPadOS13)
- Importing one file, and several files (in this case only one is imported, as before)

Everything worked fine but the case mentioned above.

**Comment by jesmrec** [comment]
### (10)

To reproduce in iPadOS13:

1. In Settings, enable "Streaming Enabled"
2. Go to file list and long press a video
3. Open video in new window

Current: Video is not streamed: black screen
Expected: Video streamed?

iPadOS13 (iPadPro)

**Comment by hosy** [comment]
> ## Re: (5) Audio Player Controls
> @hosy So, looks like you can't have both: skip X seconds AND playing next track. At least if skip is enabled, play next / previous track controls are not visible but I didn't test with headphones / CarPlay how it would behave if I trigger next / previous commands using external hardware.
> 
> Actually I loved skipping 10s back and forth since I was testing with mp3 files from my Japanese course but for music it is probably less useful.
> 
> **UPDATE**: Have a fix for this but I've seen one crash which I would like to investigate. As already said, you can't have both - skip (podcast controls) and next / previous controls visually. But you can still skip to next track from headphones. Or shall I remove podcast controls altogether? What are your preferences? May be it would be cool to infer from file metadata what controls to show and also increase skip time for example for files with longer duration. Although we could use like / dislike controls to change favourite status of item from lock screen. But may be all of that is for a separate issue cc: @michaelstingl

thank you for investigating in this issue @mneuwert 
Both is cool in my opinion and depends on the users preferences or on the media which should be played.
We can provide settings for it or we can try to detect the media type.
What do you think @mneuwert @michaelstingl ?

**Comment by hosy** [comment]
@jesmrec about (1) sounds like an iOS bug.

**Comment by hosy** [comment]
@jesmrec I cannot reproduce (2. Please can you share more details?

**Comment by mneuwert** [comment]
@jesmrec Regarding (4), yes, if the Audioplayer view is dismissed within the app, the lock screen controls are reset. Which is fine, since the app from this moment would not know which media file to play.

**Comment by michaelstingl** [comment]
> We can provide settings for it or we can try to detect the media type.
> What do you think @mneuwert @michaelstingl ?

Settings sound okay if it's low effort and doesn't clutter the UI

**Comment by mneuwert** [comment]
@michaelstingl @hosy I would like to investigate, how much information I can get from audio metadata, therefore would suggest to remove podcasts controls for now, keep next / previous track buttons and file a separate issue. How does that sound?

**Comment by mneuwert** [comment]
@jesmrec As for problem you found when testing (5), I have fixed it in latest commit. Looks like `MPNowPlayingCenter` lives it's own life and continues running internal timer even if audio is paused. Updating playerRate / elapsedTime on every `AVPlayer.pause() / play()` fixed that.

**Comment by mneuwert** [comment]
@jesmrec Regarding (10), you are not talking about **PnP** mode? Honestly, I didn't play with video streaming after multi window support has been implemented for iOS13.. Need to check

**Comment by mneuwert** [comment]
@jesmrec Issue (9) is probably something @felix-schwarz would be able to answer. I am not sure how after `OCCore.importFileNamed()` call, actual `NSURLSessionTask` instances are scheduled.

**Comment by michaelstingl** [comment]
> @michaelstingl @hosy I would like to investigate, how much information I can get from audio metadata, therefore would suggest to remove podcasts controls for now, keep next / previous track buttons and file a separate issue. How does that sound?

@mneuwert works for me

**Comment by mneuwert** [comment]
@jesmrec as for (7) I found that exporting of .mov to .mp4 is broken and is likely iOS13 bug. Nevertheless found another issue and fixed related to format conversion preventing images of being uploaded when MP4 conversion setting was active.

**Comment by jesmrec** [comment]
(1) -> you mean this is an iOS bug, will research a bit about and let you know.

(2): Try these steps out:

1. Create a folder called "My folder"
2. Try to rename it to "My folder 2"

Not posible because the cursor can not be placed at the end of the name.

(iOS13.2)

(4) -> fixed then

(10) -> 

> you are not talking about PnP mode?

no, this is regarding multi window in iPad. I hope this GIF clarifies it:

![Dec-12-2019 15-12-37](https://user-images.githubusercontent.com/14894746/70719276-fae18080-1cf1-11ea-89f2-125c4435e875.gif)

video is not played even when tapping on "play"

**Comment by mneuwert** [comment]
@jesmrec I disabled "Conversion to MPEG4" option in latest commit as agreed in the chat. So (7) is then obsolete for this release.

As for (10):
- I tested (in simulator) and it behaves strangely. If no streaming is enabled, videos are played.
- If streaming is enabled, title frame is seen, no video, but audio is playing
- If from the new window, I change into PnP, video is played
- Also, if the app is terminated, then after it is restated, state restoration takes care of restoring last valid view hierarchy and then also window with video is re-appearing. However it looses media player controls.

Looks like there are couple of bugs in iOS13 related to media playback in multi-window context.

**Comment by jesmrec** [comment]
(2) -> i think it is an iOS bug, because i reproduce it also in Files App and in Pages app. Am i worng?

(5) -> fixed

(7) -> solved

(10) -> won't fix, iOS bug

**Comment by jesmrec** [comment]
### (11)

1. Login with OAuth2
2. Start to upload a bunch of files (f.ex, an album with 50 videos)
3. While it is being uploaded, remove token (webUI -> Settings -> Security - Oauth2 -> remove iOS app as authorized)

Current: Ugly error

![IMG_1086](https://user-images.githubusercontent.com/14894746/70792274-1f446800-1d99-11ea-9da1-b2fe74c563dd.PNG)

Dialog is not dismissed neither cancelling nor retrying. It raises again.

iPhoneX v13.2
iPAdPro v13.2

**Comment by mneuwert** [comment]
### (12)
Progress view in the activity being updated is wildly jumping.

Steps to reproduce
- Start uploading bunch of photos
- Switch to status view

![ezgif-7-1eacce201291](https://user-images.githubusercontent.com/228537/70870832-8bd98580-1f98-11ea-9c59-58b6936c79a3.gif)

I think the root cause is that:
- Table view is set up to calculate height automatically
- When a new activity is added, whole table is reloaded -> recalculation of height, re-layout etc. causing jumping effect.

**Comment by jesmrec** [comment]
### (13)

After upgrading to iOS13.3, media import does not seem to work:

![Dec-18-2019 08-59-21](https://user-images.githubusercontent.com/14894746/71067421-c6981500-2174-11ea-8571-4e495369a1f9.gif)

**Comment by jesmrec** [comment]
(8) -> is fixed in iOS13.3 . But, in iOS13.2, the folder duplication shows an error of already existing item. In that case, if someone complains about the bug, do you think is enough suggesting to upgrade to 13.3?

(13) -> fixed

(11) and (12) -> moved to new issues

**Comment by jesmrec** [comment]
About (13) If i install directly from XCode (commit app 49d0ed3, commit sdk 0e9e5cc) it's working fine. But, if i archive to get a distribution apk, it is reproducible again. Does it make sense somehow?

**Comment by felix-schwarz** [comment]
@jesmrec Regarding (8): that's the old behaviour, which I preserved for anything pre 13.3. Although I'm thinking about removing that old behaviour if testing on older devices is possible. Posted this on RocketChat yesterday:

> I feel like that may have been the issue due to which folder duplication didn't work in iOS 12, either. If you have a test device running iOS 12, I'd remove the special pre-13.3 branch in the code that currently blocks folder duplication in those versions. You could then give it a try - and if it works, that feature would become available for iOS 12 users, too.

Do you have a testing device with iOS 12?

If testing is not possible, then I think telling users to upgrade to iOS 13.3 to gain that feature would be appropriate.

**Comment by jesmrec** [comment]
i have iOS12 testing devices. will check

**Comment by jesmrec** [comment]
i've tested the current `milestone-1.2` branch in iOS12 device (Files app duplication), and the result is:
<img width="341" alt="Screenshot 2019-12-20 at 08 42 04" src="https://user-images.githubusercontent.com/14894746/71238545-a13a1100-2304-11ea-8a8b-b3f9353a4230.png">

**Comment by jesmrec** [comment]
(13) fixed after tweaking the optimization compiler. 

Performed upgrading tests from 1.1.2, with succesful results.

Approved on my side.

The [WONT FIX] reports will be addressed in separated issues.
