### ISSUE TITLE
[RELEASE] 1.3

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#598]
Release a new version
### Git & Code

- [x] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [x] [TRFX] Update translations from transifex branch.
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [DEV] Update In-App Release Notes (changelog) in ownCloud/Release Notes/ReleaseNotes.plist
- [x] [QA] Design Test plan
- [x] [QA] Regression Test plan
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [x] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

If it is required to update the iOS-SDK version:

- [x] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code)
- [ ] [mail] inform #marketing about the new release.
- [ ] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [ ] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [x] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [x] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [x] [DIS] Upload the binary to the App Store
- [x] [DIS] App Store Connect: Trigger release (manually)
- [x] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [x] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [x] [DIS] App Store Connect: Update changelogs
- [x] [DIS] App Store Connect: Submit for review

## QA

Test plan:

https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%201.3.0/Regression.md

## BUGS & IMPROVEMENTS:

- [X] (1) Icons missed in `What's new` https://github.com/owncloud/ios-app/issues/598#issuecomment-584549584 [FIXED]
- [X] (2) iOS13 features in iOS12 `What's new` https://github.com/owncloud/ios-app/issues/598#issuecomment-584552672 [WONT FIX]
- [X] (3) Camera uploads stucked from archived ipa https://github.com/owncloud/ios-app/issues/598#issuecomment-584599451 [FIXED]
- [X] (4) New document from MSOffice https://github.com/owncloud/ios-app/issues/598#issuecomment-584614427

**Comment by jesmrec** [comment]
### (1)

1. Install 1.2.1
2. Set Classic/Light theme
3. Upgrade to 1.3.0

Current:  `What's new` is displayed but icons are missed 
Expected: `What's new` is correct

| Dark | Classic | Light |
| :-: | :-: | :-: |
|![Screen Shot 2020-02-11 at 10 33 49](https://user-images.githubusercontent.com/14894746/74224946-0e8d7100-4cba-11ea-8e39-d94721ce762d.png)|![Screen Shot 2020-02-11 at 10 31 05](https://user-images.githubusercontent.com/14894746/74224822-d7b75b00-4cb9-11ea-9b46-afd6f88f332f.png)|![Screen Shot 2020-02-11 at 10 40 53](https://user-images.githubusercontent.com/14894746/74225490-1b5e9480-4cbb-11ea-847d-8d467f903ddc.png)

**Comment by jesmrec** [comment]
### (2)

Users with iOS12 will see in the `What's new` all the features that will not be available in such version (scanner, shortcuts, markup). Should them be hidden depending on the version? (if feasible)

**Comment by jesmrec** [comment]
### (3)

Camera uploads are not behaving in the same way, depending whether the app is installed from XCode or from an archived ipa.

In case of an archived ipa, the pics are stucked in status view as `Media Import`

Here it is the difference:

| From XCode | From archived ipa | 
| :-: | :-: | 
|![Feb-11-2020 12-44-28-Xcode](https://user-images.githubusercontent.com/14894746/74234382-fa06a400-4ccc-11ea-9018-91170eed3927.gif)|![Feb-11-2020 12-47-14-Archive](https://user-images.githubusercontent.com/14894746/74234396-00951b80-4ccd-11ea-9644-8c95b10e7056.gif)|

both gifs were taken with the same commit: `8ebbcfb` and an iOS13 device.

**Comment by jesmrec** [comment]
### (4)

1. Open Files App, ownCloud account
2. Long press over a file and select `Copy` 

Current: nothing happens

![Feb-11-2020 12-44-28-Xcode](https://user-images.githubusercontent.com/14894746/74236223-0f7dcd00-4cd1-11ea-8bdc-e133000ecedb.gif)

Expected: folder picker dialog to copy to

iOS13 (iPhoneXR)

commit `8ebbcfb`

**Comment by jesmrec** [comment]
### (4)

1. Open Word app
2. Create a new document
3. Save to oC

Current: zero bytes document 

![Feb-11-2020 13-34-48](https://user-images.githubusercontent.com/14894746/74237225-58cf1c00-4cd3-11ea-9f69-9d1a58d5c639.gif)

Expected: correct document

iOS13 iPhone XR
 commit: `8ebbcfb`

probably related with https://github.com/owncloud/enterprise/issues/3803#issue-557337146

**Comment by hosy** [comment]
@jesmrec (1) is fixed
(2) I think this is not a problem, because iOS 13 features will be named in the release notes, that this depends on the iOS version. On the App Store release notes all features are mentioned too.

**Comment by jesmrec** [comment]
(1) fixed

**Comment by hosy** [comment]
@jesmrec (3) disabled optimization levels again in SDK to prevent Xcode bug. Please check this problem again, with the latest commit 2860441

**Comment by jesmrec** [comment]
thanks for checking! (3) is fixed

**Comment by felix-schwarz** [comment]
Regarding (4) @jesmrec @hosy:

Here's what I found out:

### Retrospective
The last time we had a zero-sized Word document issue, Word saved files this way:
1) Word tells the FP to import the new document, but only provides a 0-byte file
2) *Word actually saves file*
3) Word tells the FP that there's an update to the document (now with actual contents)

Back then, 3) triggered a race-condition, which has since been fixed.

### Today
Today, Word behaves differently:
- Word still tells the FP to import the new document, but only provides a 0-byte file
- it no longer follows up with actually saving the file and notifying the FP about a change
- once the user closes the document, Word actually saves the file and notifies the FP that there's an update to the document
- at that point, the file is saved to the server as expected

### Reproducability
Saving a file to iCloud Drive also produces a zero-sized file until closing the document:

![Bildschirmfoto 2020-02-12 um 11 43 24](https://user-images.githubusercontent.com/639669/74327680-e1f65980-4d8c-11ea-996d-9400f17f31ae.png)


### Conclusion
This does not appear to be a bug in the File Provider. Instead, Word simply doesn't provide any file contents to the FileProvider until the user closes the document.

Microsoft likely tries to avoid unnecessary traffic by not saving copies until the user actually is finished working on a file. While I'm not sure that's a good way to achieve that, I'm pretty sure we can do nothing about it. 😕

**Comment by michaelstingl** [comment]
> Microsoft likely tries to avoid unnecessary traffic by not saving copies until the user actually is finished working on a file. While I'm not sure that's a good way to achieve that, I'm pretty sure we can do nothing about it. 😕

Word settings look they're doing "Autosave". I'd expect they actually save data to the document during editing, not only when you close the document 🤔 . Does the 0-byte file already has a "real" file name? Or is it a temporary name with "`~`" or something?

**Comment by felix-schwarz** [comment]
It has the real filename. What's odd is that even "Save a copy" in Word sends a zero-sized file to the File Provider and also only provides actual content when closing the document.

**Comment by felix-schwarz** [comment]
As far as Auto-Save is concerned, Microsoft writes "Änderungen werden automatisch in iPhone gespeichert" (sic), which is either really bad wording - or a hint that auto-save only happens locally.

**Comment by michaelstingl** [comment]
Word bugs from my pov

**Comment by felix-schwarz** [comment]
Likewise, turning off Auto-Save and hitting `Save` directly also doesn't send any command to the File Provider.

The only thing that it *does* send (and we don't currently support), however, is to update the "last used" date. Right now, we return a "not supported" error for that, so I considered that Word might not update the file because of that. However, even returning "success" here wouldn't make Word notify the FP about changes or save the file. And at the time the "set last used date" command was called, the file on disk was also still zero-sized.

**Comment by felix-schwarz** [comment]
> Word bugs from my pov

Yep. I think so, too.

**Comment by jesmrec** [comment]
From my side, tests are passed

**Comment by hosy** [comment]
@settermjd we have a lot of new features in version 1.3.0 which needs documentation. If you need an introduction, please ping me. Thank you!

**Comment by cdamken** [comment]
@felix-schwarz @michaelstingl  if the autosave is disabled works in the proper way?

if that is the case: Is there any way to detect it? we could send some warnings in the app? or in a readme?

**Comment by felix-schwarz** [comment]
@cdamken Word shows the same behaviour when disabling autosave and tapping "Save": the actual file is only saved back to the cloud/File Provider when the user closes the document.

Unfortunately, there's nothing we can do about it from our side. It's a Word implementation detail that equally applies regardless of which File Provider people use.

Since iOS apps don't have access to the list of running processes or access to the sandboxes of other apps, it's not possible to detect and warn users about this Word behaviour.

**Comment by michaelstingl** [comment]
@jesmrec @felix-schwarz I’ve got a report, that MS Word for iOS update 2.3.4 from Februar, 10th, fixed the problem. Thanks @cdamken for the feedback.
