### ISSUE TITLE
[FEATURE REQUEST] Improve Public Link Creation

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#671]
## Copy Link to Clipboard

Created link should be copied to clipboard automatically when the link was created.

## Show Clear Button on Public Link Name text field

The text field for the public link name should always show the clear button for a faster deletion

## Dragging Link
In the Public Link Overview, it should be possible to drag a created link to a third party app on iPad.

### How it should work:
- Long tap on public link item
- Dragging item is enabled
- Drag item outside of the app

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
