### ISSUE TITLE
[FEATURE REQUEST] Use ReplayKit for Screen Recording/Broadcasting

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#692]
With ReplayKit it is possible to record the iOS screen, with and without Audio.

This could be very useful if you want to share your screen with others.

There are two possibilities:
- Save recorded screen to file
- Live broadcast

## Save recorded screen to file
This should be not so complex to implement

## Live Broadcast
This step needs also a server component. Maybe this could be implemented by ourself or we can finde a tool.
But this feature could be very huge. You can offer a screen sharing to all or selected OC users of an instance. Therefore this is a great tool for presenting and collaborate.

### TASKS

- [x] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)
