### ISSUE TITLE
[FEATURE REQUEST] feature/open _private_link milestone/1.4

### ISSUE THREAD

**Issue by laurietheresa** [owncloud/ios-app#703]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_name
- [ ] Development tasks
  - [x] Implement whatever
  - [ ] ...
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [x] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)change iOS passcode
