### ISSUE TITLE
[RELEASE] 11.4

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#716]
Release a new version
### Before merging into master

- [ ] Be sure to remove/rename `ownCloud/Resources/Theming/Branding.plist` before merging!

### Git & Code

- [x] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [x] [TRFX] Update translations from transifex branch.
- [x] [TRFX] Check for missing translations. Ping @cscherm
- [ ] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [ ] [DEV] Update In-App Release Notes (changelog) in ownCloud/Release Notes/ReleaseNotes.plist
- [x] [QA] Design Test plan
- [x] [QA] Regression Test plan 
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [ ] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

If it is required to update the iOS-SDK version:

- [x] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code)
- [ ] [mail] inform #marketing about the new release.
- [x] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [ ] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [ ] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [ ] [DIS] Upload the binary to the App Store
- [ ] [DIS] App Store Connect: Trigger release (manually)
- [ ] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [ ] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [ ] [DIS] App Store Connect: Update changelogs
- [ ] [DIS] App Store Connect: Submit for review

## QA

Regression test: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2011.4.0/Regression%2011.4.md

### BUGS & IMPROVEMENTS:

- [X] [1) Contents from Cache (after re-authentication) https://github.com/owncloud/ios-app/issues/716#issuecomment-673422185) [FIXED]
- [X] (2) Duplication with no quota https://github.com/owncloud/ios-app/issues/716#issuecomment-674721785 [FIXED]
- [X] (3) Missing accounts in Shortcuts app https://github.com/owncloud/ios-app/issues/716#issuecomment-675425844 [FIXED]
- [X] (4) Empty row in Settings https://github.com/owncloud/ios-app/issues/716#issuecomment-676106311 [FIXED]
- [X] (5) Theme is lost after upgrading https://github.com/owncloud/ios-app/issues/716#issuecomment-676117598 [FIXED]

**Comment by hosy** [comment]
## (1) Contents from Cache (after re-authentication)

If a token is expired I get a re-authentication inside the file list. After re-authentication the account still keeps in offline mode and shows "Contents from Cache". Pull-to-refresh does not update the content.
I need to switch back to the account list and select the account again to update it.
// @felix-schwarz 

![ezgif-6-7e7b485b3fb1](https://user-images.githubusercontent.com/736109/90117183-da713680-dd56-11ea-92ec-f4c2057a3f71.gif)

**Comment by felix-schwarz** [comment]
@hosy (1) should be fixed now as of 65fcca44449091139afdb5b3fcc3481d1ef479da.

**Comment by jesmrec** [comment]
### (2) 

1. Set an account, so that the quota is close to be reached
2. In Files app, duplicate a file whose size will exceed the quota -> notification pops up about the lack of storage in the account
3. In web, increase the quota for the user to have enough storage to complete the operation
4. In app, go to "Status" and retry the action

Current: action is stucked
Expected: action is completed

It happens if the duplication is done in Files App. Duplication in the app does not reproduce the problem.

iPhoneXR v13.6
commit `7835b60`

**Comment by felix-schwarz** [comment]
@jesmrec Regarding (2), what happens if you go back to the Files app? Does it get unstuck?

**Comment by jesmrec** [comment]
If i go back to Files app, it is not unstucked. It is shown in Files app as `Waiting to upload`

**Comment by felix-schwarz** [comment]
@jesmrec Thanks for checking! 

What happens if you browse files (and other directories) in the affected account in the Files.app?

If that doesn't unstuck it either: does a reboot of the device unstuck it?

**Comment by jesmrec** [comment]
Browsing files and folders in the same app -> it does not unstuck the file

Killing the app and reopening -> it does not unstuck the file

Rebooting the device -> it unstucks the file.

**Comment by felix-schwarz** [comment]
@jesmrec I just pushed a change that reverts a fix I added with `feature/diagnostics` that I wasn't sure about then, and that could be related. Please re-check with commit https://github.com/owncloud/ios-app/pull/648/commits/e05075d7685da94b8cf9fcee48221ebe0aa95cd5 if the issue is still present.

**Comment by jesmrec** [comment]
(2) fixed with the latest commit

(1) fixed as well

**Comment by jesmrec** [comment]
### (3)

1. Add an enterprise account (f. ex. `demo.owncloud.com`), or purchase the Shortcuts app
2. Open Shortcuts app
3. Try to create a simple shortcut: create a folder in root folder of any account

Current: List of accounts is empty:

![Screenshot 2020-08-18 at 13 28 49](https://user-images.githubusercontent.com/14894746/90508031-37a22900-e157-11ea-91cd-c3823401651f.png)

Expected: In `version_1.3.2` , a list of available accounts is displayed in the dropdown to select in which one is going to be executed

iPadAir v13, iPhoneXR v13
commit `8b94c27`

**Comment by jesmrec** [comment]
(3) fixed

**Comment by jesmrec** [comment]
### (4)

There is an empty row in the `More` section of Settings view:

![Screenshot 2020-08-19 at 12 28 03](https://user-images.githubusercontent.com/14894746/90623975-8adbb080-e217-11ea-98fd-21265740fda9.png)

**Comment by jesmrec** [comment]
### (5)

1. Install latest version `1.3.2`
2. In settings, set a different theme (Classic, Light or System)
3. Upgrade to 11.4

Current: After upgrading, dark theme is set
Expected: After upgrading, the selected theme stays on.

iPadAir v13, iPhoneXR v13
commit `50eb0121`

**Comment by hosy** [comment]
@jesmrec (4) is fixed with e60383d

**Comment by felix-schwarz** [comment]
@jesmrec (5) should be fixed with 43691f7ac788481a3943dbd5cb2ee037ae557830.

**Comment by jesmrec** [comment]
(4) and (5) fixed

**Comment by jesmrec** [comment]
Version approved. 

Approved commits:

App: `43691f7ac`
SDK:  `164fbefa`

Great job, team!
