### ISSUE TITLE
[FEATURE REQUEST] Contextual Menu in File List

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#717]
Implement a contextual menu for all _More Menu Items_ to provide a context menu for iPad right click or long press on a file list item.

iOS 13 provides a contextual menu, which is already implemented in the account list.

### TASKS

- [x] Create branch feature/contextual-menu
- [x] Development
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
Done! ready for 11.4
