### ISSUE TITLE
[FEATURE REQUEST] Add "Compress/Uncompress" Action

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#719]
As a user I want to have an action to compress selected file list items to a (password protected) zip file.
As a user I want to uncompress a (password protected) zip file into my account.

As a user I want to do this also with a Shortcut.app action.

**Describe the solution you'd like**
Provide an action for this tasks.
### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/un-compress
- [ ] Development tasks
  - [ ] File list Actions
  - [ ] Shortcut Actions
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library 
- Intent

**Comment by michaelstingl** [comment]
This `*.ZIP` explodes when uncompressing it in the iOS Files app:
- [mimetypemapping_dist.zip](https://github.com/owncloud/ios-app/files/13365513/mimetypemapping_dist.zip)
  (204x 0kb files… 🙈)

**Comment by michaelstingl** [comment]
SDK would need to import / replicate folder structures from imports.
