### ISSUE TITLE
[FEATURE REQUEST] Add additional Grid View Layout in File List

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#744]
**Describe the solution you'd like**
The file list should have an option to switch from the list layout to the grid view layout. 
- add a button or menu entry to switch between both views
- in grid view show preview images in a large view
- adopt grid view columns to the device screen size
- add a possibility to change the grid view size
- do not show all item informations in grid view or add an option to hide/show informations

### TASKS

- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by hosy** [comment]
I had a meeting with @felix-schwarz about the grid view and we decided to refactor the current `UITableView` class.
As a result we want to move code into a new Datasource class to get a better MVC structure.
This is needed, because iOS 12 and iOS 13 do not support the new UICollectionView changes, which are available since iOS 14.
This means we have to implement two code paths and this is easier with moving code into a datasource class.

This needs more development time and can break, so it makes sense to move it to milestone 11.8.
//cc @michaelstingl

**Comment by michaelstingl** [comment]
> This means we have to implement two code paths and this is easier with moving code into a datasource class.

Okay. Should be easy to remove the legacy codepath when we decide to drop it. Maybe @jesmrec can add some UI tests around it?? (basic operations, we can discuss…)

> This needs more development time and can break, so it makes sense to move it to milestone 11.8.
> //cc @michaelstingl

works for me
