### ISSUE TITLE
[FEATURE REQUEST] Revert Streaming option, make Streaming the default ^

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#766]
![IMG_3075](https://user-images.githubusercontent.com/214010/88944110-a133c380-d28c-11ea-9633-63a375e324bb.jpg)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
Setting is working as expected.

Fresh installation:

- [X] Enabled -> Download
- [X] Disabled -> Streaming 

Upgrade 

- [X] Enabled (Streaming) -> Disabled (Streaming) 
- [X] Disabled (Download) -> Disabled (Streaming) (accepted as is)

On the other hand: in the list of accounts, the cloud icon is missing:

![Screenshot 2020-08-10 at 14 37 45](https://user-images.githubusercontent.com/14894746/89783656-9b08d700-db17-11ea-91e8-ec77e717faa0.png)

**Comment by mneuwert** [comment]
@jesmrec this must be an issue with `milestone/1.4` intermediate bug which @hosy fixed meanwhile. I will merge latest `milestone/1.4` changes again.

**Comment by mneuwert** [comment]
@jesmrec After merging `milestone/1.4`, cloud icon is back

**Comment by jesmrec** [comment]
Right. Approved.
