### ISSUE TITLE
[RELEASE] 11.4.1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#790]
Release a new version

Xcode version to work with: `11.7 (11E801a)`

### Git & Code

- [x] [GIT] Create branch `release/11.4.1` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `11.4.1` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [ ] [TRFX] Update translations from transifex branch.
- [ ] [TRFX] Check for missing translations. Ping @cscherm
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [DEV] Update In-App Release Notes (changelog) in ownCloud/Release Notes/ReleaseNotes.plist
- [x] [QA] Design Test plan
- [x] [QA] Regression Test plan
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [x] [GIT] Merge branch `release/11.4.1` in master
- [x] [GIT] Create tag and sign it `11.4.1`
- [x] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

If it is required to update the iOS-SDK version:

- [x] [GIT] Create branch library `release/11.4.1`(freeze the code)
- [ ] [mail] inform #marketing about the new release.
- [ ] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [ ] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [x] [GIT] Merge branch `release/11.4.1` in `master`
- [ ] [GIT] Create tag and sign it `11.4.1`
- [ ] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `11.4.1`
- [x] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [x] [DIS] Upload the binary to the App Store
- [x] [DIS] App Store Connect: Trigger release (manually)
- [x] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [x] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [x] [DIS] App Store Connect: Update changelogs
- [x] [DIS] App Store Connect: Submit for review

## BUGS & IMPROVEMENTS:

- [x] fix #782 
- [x] fix #747
- [x] fix #793 
- [x] only show purchases section if there's at least one non-Enterprise account
- [ ] add "Replace" option for uploads

## QA

Regression test: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2011.4.1/Regression.md

- [x] (1) Keyboard issue after wrong URL https://github.com/owncloud/ios-app/issues/790#issuecomment-699881919 [FIXED]
- [x] (2) Contextual menu hides the bottom bar items behind actions https://github.com/owncloud/ios-app/issues/790#issuecomment-700519176 [FIXED]
- [X] (3) Uploads in oCIS https://github.com/owncloud/ios-app/issues/790#issuecomment-700524331 [OUT OF SCOPE]

**Comment by hosy** [comment]
### (1) Keyboard issue after wrong URL

1) enter wrong server URL https://test.owncloud.org/
2) Confirm error (OK) with ⌘1
==> can’t go back to URL field with keyboard (my muscle memory tried ⌘L from browser URL bar)

**Comment by hosy** [comment]
@jesmrec (1) is fixed with ed3c0f9eef4f29d18111acaabcae756f108743f8

**Comment by jesmrec** [comment]
### (2)

1. Open contextual menu over any item of the list
2. Close contextual menu by clicking out

Current: In the bottom bar: actions (copy, move, delete..). Regular menu appears again by closing/opening the bookmark

![Sep-29-2020 09-48-30](https://user-images.githubusercontent.com/14894746/94528951-6a047300-0239-11eb-819a-3528b21febd0.gif)

Expected: in the bottom bar: `Browse`, `Quick access` and `Status`

iPhoneXR v13.7
app commit: `c891c9c9`

**Comment by jesmrec** [comment]
### (3)

I've tried to upload a file to `ocis.owncloud.works` (current oCIS test server) and result was a 404, no way to upload. Is this expected at this moment because something pending to implement? 

CC @felix-schwarz @michaelstingl

**Comment by jesmrec** [comment]
@hose, the fix about (1). Which is the keyboard shortcut that set cursor in the URL field after the fix?

**Comment by hosy** [comment]
> @hosy , the fix about (1). Which is the keyboard shortcut that set cursor in the URL field after the fix?

@jesmrec long press the command key. After the fix there is a new entry `Select next` `⌘` + `↓`. This shortcut should select the text field.

**Comment by michaelstingl** [comment]
> ### (3)
> I've tried to upload a file to `ocis.owncloud.works` (current oCIS test server) and result was a 404, no way to upload. Is this expected at this moment because something pending to implement?

@jesmrec Needs a new issue and a closer look from the experts…

**Comment by jesmrec** [comment]
> > @hosy , the fix about (1). Which is the keyboard shortcut that set cursor in the URL field after the fix?
> 
> @jesmrec long press the command key. After the fix there is a new entry `Select next` `⌘` + `↓`. This shortcut should select the text field.

Thanks, (1) is fixed.

**Comment by jesmrec** [comment]
> @jesmrec Needs a new issue and a closer look from the experts…

i will open this issue after 11.4.1 in case it is not opened yet. The point is, that this is out of scope here. Thanks.

**Comment by jesmrec** [comment]
From my side, the 11.4.1 is approved.

Approved commits:
 - app: `02b31c5c``
 - sdk: `6c22500`

Xcode version: `11.7 (11E801a)`

**Comment by michaelstingl** [comment]
> ### (3) [out of scope]
> I've tried to upload a file to `ocis.owncloud.works` (current oCIS test server) and result was a 404, no way to upload. Is this expected at this moment because something pending to implement?

@jesmrec @C0rby found config issue on `ocis.owncloud.works`. Should work again.

**Comment by jesmrec** [comment]
Ok i will check it then

**Comment by jesmrec** [comment]
> @jesmrec @C0rby found config issue on ocis.owncloud.works. Should work again.

now it works. Thanks!!

**Comment by jesmrec** [comment]
Done!
