### ISSUE TITLE
[RELEASE] 11.4.2

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#827]
Release a new version

Xcode version to work with: 12.1 (12A7403)

### Git & Code

- [x] [GIT] Create branch `release/11.4.2` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `11.4.2` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [ ] [TRFX] Update translations from transifex branch.
- [ ] [TRFX] Check for missing translations. Ping @cscherm
- [ ] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [DEV] Update In-App Release Notes (changelog) in ownCloud/Release Notes/ReleaseNotes.plist
- [x] [QA] Design Test plan
- [x] [QA] Regression Test plan
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [ ] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

If it is required to update the iOS-SDK version:

- [x] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code)
- [ ] [mail] inform #marketing about the new release.
- [ ] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [ ] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [ ] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [ ] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [ ] [DIS] Upload the binary to the App Store
- [ ] [DIS] App Store Connect: Trigger release (manually)
- [ ] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [ ] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [ ] [DIS] App Store Connect: Update changelogs
- [ ] [DIS] App Store Connect: Submit for review

## QA

Regression test: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2011.4.2/Regression.md 

BUGS & IMPROVEMENTS:

- [X] (1) Photo picker selector https://github.com/owncloud/ios-app/issues/827#issuecomment-721572634 [FIXED]
- [X] (2) Offline creation of items https://github.com/owncloud/ios-app/issues/827#issuecomment-721584879 [FIXED]
- [X] (3) Alert with a white band https://github.com/owncloud/ios-app/issues/827#issuecomment-721592573 [FIXED]
- [x] (4) Unresponsive buttons https://github.com/owncloud/ios-app/issues/827#issuecomment-721608870 [FIXED]

**Comment by jesmrec** [comment]
### (1)

iOS13: In the Photo upload picker, pics and videos can be selected by swiping with the finger, not selecting one by one
iOS14: This feature does not work.

CC @mneuwert (you implemented that, didn't you? )

**Comment by jesmrec** [comment]
### (2)

1. Remove connection from device
2. Create a folder (no matter the name)

Current: folder recently created does not appear in the list. You have to browse out of the folder and browse in again to see it there.
11.4.1: folder appears in the list, greyed out.

NOTE: Not only a folder creation, also other operations that create new stuff (move, copy...) 

iOS14.1

CC @felix-schwarz

**Comment by jesmrec** [comment]
### (3)

Set maintenance mode (`occ maintenance:mode --on`)

Here, two effects:

- When account in the server is open, alert is displayed twice instead of once (this is not a regression, it happened in 11.4.1, so we can move it to a separate ticket. up to you)
- Alert shows a white band on the bottom (in dark theme):

![Screenshot 2020-11-04 at 09 35 19](https://user-images.githubusercontent.com/14894746/98088244-82435f80-1e81-11eb-9de0-bc63dc4e391a.png)

iOS14.1

**Comment by jesmrec** [comment]
### (4)

I got unresponsiveness button in the following scenarios:

![Screen Shot 2020-11-04 at 10 01 37](https://user-images.githubusercontent.com/14894746/98090975-0ea35180-1e85-11eb-97cf-d8c490e2657c.png)

no matter which button you click (`Retry`, `Cancel`), it does not respond. Bottom navigation bar works, so you can move to other places in the app. These are the steps:

1. Copy a file to folder which contains a file with same name / upload a file which size exceeds the quota
2. Go to status to solve the errors and select any of the options (`Retry`, `Cancel`) -> app does not respond
3. Select another tab (browse, quick access), and browse back to status -> buttons are now responsive

iPhoneXR iOS14.1
`cdb3fc2a`

**Comment by mneuwert** [comment]
> ### (1)
> 
> 
> 
> iOS13: In the Photo upload picker, pics and videos can be selected by swiping with the finger, not selecting one by one
> 
> iOS14: This feature does not work.
> 
> 
> 
> CC @mneuwert (you implemented that, didn't you? )
> 
> 
> 
> iPhoneXR iOS14.1
> 
> `cdb3fc2a`

I will check this..

**Comment by felix-schwarz** [comment]
> ### (2)
> 1. Remove connection from device
> 2. Create a folder (no matter the name)
> 
> Current: folder recently created does not appear in the list. You have to browse out of the folder and browse in again to see it there.
> 11.4.1: folder appears in the list, greyed out.
> 
> Not a bad behaviour (folder is created when connection is recovered). Just the difference with previous version.
> 
> NOTE: Not only a folder creation, also other operations that create new stuff (move, copy...)

Good catch! That behavior depended on whether you entered a new session while offline (in which case new items wouldn't appear) vs. going offline while in a session (in which case new items would appear). Fixed that with fc49eb4.

**Comment by hosy** [comment]
> ### (3)
> Set maintenance mode (`occ maintenance:mode --on`)
> 
> Here, two effects:
> 
> * When account in the server is open, alert is displayed twice instead of once (this is not a regression, it happened in 11.4.1, so we can move it to a separate ticket. up to you)
> * Alert shows a white band on the bottom (in dark theme):
> 
> ![Screenshot 2020-11-04 at 09 35 19](https://user-images.githubusercontent.com/14894746/98088244-82435f80-1e81-11eb-9de0-bc63dc4e391a.png)
> 
> iPhoneXR iOS14.1
> `cdb3fc2a`

@jesmrec  Fixed with commit https://github.com/owncloud/ios-app/pull/812/commits/8a721914babb4f16f747a6382ffac886c75f8114

**Comment by felix-schwarz** [comment]
> ### (4)
> I got unresponsiveness in buttons from the following scenarios:

I'm sorry, but I couldn't reproduce this. What I did:
1) Copy `Example.odt` to the root dir twice, tap on the "empty" space above the error message that pops up to close it without answering it
2) Set a tight quota of 10 MB on  the account
3) Upload large photos from the photo library
4) When the quota error comes up, tap on the "empty" space above the error message that pops up to close it without answering it
5) Go to `Status` tab
6) Tap on `Cancel` (in random order) until all messages are answered - which works as it should.

Please let me know if your process differed, as I can't reproduce the issue with these steps.

**Comment by jesmrec** [comment]
@felix-schwarz these are the correct steps. I can reproduce this with only one conflict (this will make it easier). Some exrta details i have discovered about this:

I was able to reproduce with iPhoneXR 14.1 and with emulator (iPhone8 v14.1).
It was reproduced after a fresh install. After reproducing it the first time, it does not happen anymore.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/14894746/98138208-27325c80-1ec3-11eb-8604-720f1515d83e.gif)

If with these tips you can not reproduce, we can open a new ticket to handle it separately and not block the release.

**Comment by mneuwert** [comment]
> ### (1)
> iOS13: In the Photo upload picker, pics and videos can be selected by swiping with the finger, not selecting one by one
> iOS14: This feature does not work.
> 
> CC @mneuwert (you implemented that, didn't you? )
> 
> iPhoneXR iOS14.1
> `cdb3fc2a`

Committed a workaround for this issue. Definitely works when compiled with Xcode 12 and linked against iOS 14 SDK, but I suspect it won't work otherwise

**Comment by jesmrec** [comment]
(1) -> fixed
(2) -> fixed
(3) -> fixed

**Comment by felix-schwarz** [comment]
@jesmrec I just fixed the issue with 93f75278c7bc5a1bf62104cb21b7ecc5acdd2505.

The issue was that we had added the `AlertView` directly as subview of the `UITableViewCell`. Depending on timing, `UITableViewCell` would then add an transparent content view on top, blocking all taps:

![Bildschirmfoto 2020-11-05 um 13 57 04](https://user-images.githubusercontent.com/639669/98245896-e1809d00-1f71-11eb-9132-d33f53269014.png)

When it worked, it would be the other way round and `AlertView` would sit on top:

![Bildschirmfoto 2020-11-05 um 13 57 27](https://user-images.githubusercontent.com/639669/98245939-ee04f580-1f71-11eb-8038-291ef81ae2fc.png)

I've now changed the code so that `AlertView` is a subview of the content view, so issues due to ordering can't happen anymore:

![Bildschirmfoto 2020-11-05 um 14 10 08](https://user-images.githubusercontent.com/639669/98246015-0412b600-1f72-11eb-9444-7b6630ee406b.png)

**Comment by jesmrec** [comment]
(4) is fixed

**Comment by jesmrec** [comment]
Release is approved on my side

Commits approved:

app: `93f7527`
SDK: `40f6000`

Xcode version: `12.1 (12A7403)`

great job team!
