### ISSUE TITLE
[FEATURE REQUEST] Passcode UI for File Provider

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#880]
**Is your feature request related to a problem? Please describe.**
The app can be secured by setting a pass code. This pass code is also present inside the file provider extension. If the pass code delay is set to `Immediately` the user cannot get access to the files inside the file provider.

**Describe the solution you'd like**
There is a possibility to add a file provider UI, which should show the passcode UI to get access to the files, when the passcode was correct entered.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_name
- [x] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by hosy** [comment]
Some research for this problem:

<img width="787" alt="Bildschirmfoto 2021-01-28 um 13 04 19" src="https://user-images.githubusercontent.com/736109/106136591-cd5fcc80-6169-11eb-910f-c2503972033a.png">
<img width="925" alt="Bildschirmfoto 2021-01-28 um 13 06 48" src="https://user-images.githubusercontent.com/736109/106136613-d2248080-6169-11eb-86da-5dd5f21c47f8.png">

**Comment by hosy** [comment]
This could mean, we need an `FileProviderExtensionUI` before we can get this error message and hopefully to show an own UI.
