### ISSUE TITLE
[RELEASE] ios-app 11.5.0

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#886]
Release a new version

Xcode version to work with:
Version 12.2 (12B45b)

### Git & Code

- [x] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [x] [TRFX] Update translations from transifex branch.
- [ ] [TRFX] Check for missing translations. Ping @cscherm
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [DEV] Update In-App Release Notes (changelog) in ownCloud/Release Notes/ReleaseNotes.plist
- [x] [QA] Design Test plan
- [X] [QA] Regression Test plan
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [x] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

If it is required to update the iOS-SDK version:

- [x] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code)
- [ ] [mail] inform #marketing about the new release.
- [ ] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [x] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [x] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [x] [DIS] Upload the binary to the App Store
- [x] [DIS] App Store Connect: Trigger release (manually)
- [x] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [ ] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [x] [DIS] App Store Connect: Update changelogs
- [x] [DIS] App Store Connect: Submit for review

## QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2011.5/Regression_11.5.md

#### BUGS & IMPROVEMENTS:

- [x] (1) 301 Redirections are not correctly handled https://github.com/owncloud/ios-app/issues/886#issuecomment-772337148 [FIXED]
- [x] (2) 302 redirection runs into infinite loop https://github.com/owncloud/ios-app/issues/886#issuecomment-772340603
- [x] (3) Glitch in token renewal https://github.com/owncloud/ios-app/issues/886#issuecomment-772370127 [FIXED]
- [X] (4) (improvement) Select all in new picker https://github.com/owncloud/ios-app/issues/886#issuecomment-772449817 [WONT FIX]
- [x] (5) Alignment of three-dot-button is lost https://github.com/owncloud/ios-app/issues/886#issuecomment-772476674 [WONT FIX]
- [x] (6) Import from Share Sheet https://github.com/owncloud/ios-app/issues/886#issuecomment-773973380 [NOT REPRODUCIBLE]
- [X] (7) After upgrading, sessions are lost https://github.com/owncloud/ios-app/issues/886#issuecomment-774987707 [FIXED]
- [X] (8) Logging is disable after upgrading https://github.com/owncloud/ios-app/issues/886#issuecomment-776554542 [FIXED]

**Comment by jesmrec** [comment]
### (1) 

Bad behaviours in redirections

- With redirection 301, after server returns `301` with a correct location, app shows:

![Screenshot 2021-02-03 at 09 41 42](https://user-images.githubusercontent.com/14894746/106720750-1d281300-6604-11eb-8479-c7f1261d77a0.png)

and it stops.

**Comment by jesmrec** [comment]
### (2)

With 302 redirection, the app runs into infinite loop

1. App checks `/status.php` -> server returns: `Location:        http://<url>/stable10/status.php`
2. App checks `http://<url>/stable10/status.php` -> server returns 200
3. App checks again `/status.php` and goes to step 1.

App `8bc2d1b1`
SDK `5a70106`
iPhoneXR v14.2

**Comment by felix-schwarz** [comment]
@jesmrec The log for (1) doesn't seem to contain any HTTP requests.

**Comment by jesmrec** [comment]
301 logs: 
[ownCloud_3_Feb_2021_at_10_12_15.log.txt](https://github.com/owncloud/ios-app/files/5917263/ownCloud_3_Feb_2021_at_10_12_15.log.txt)

302 logs:
[ownCloud_3_Feb_2021_at_10_13_51.log.txt](https://github.com/owncloud/ios-app/files/5917271/ownCloud_3_Feb_2021_at_10_13_51.log.txt)

**Comment by jesmrec** [comment]
### (3)

An small glitch when OAuth2 token expires.

The request to token endpoint is sent twice:

![Screenshot 2021-02-03 at 10 30 58](https://user-images.githubusercontent.com/14894746/106726949-3e403200-660b-11eb-9a27-ccd00886ab9e.png)

First one, everything works fine. Token is renewed and new refresh token is granted
Second one uses the same refresh token as the first one. That token is not valid anymore, since first request granted a new one, so it returns `400` causing this visual effect:

![Screenshot 2021-02-03 at 10 26 07](https://user-images.githubusercontent.com/14894746/106727176-7b0c2900-660b-11eb-9142-0dc9137a65bc.png)

But, session goes on with the token granted in first request

App `8bc2d1b1`
SDK `5a70106`
iPhoneXR v14.2

Logs:
[Uploading ownCloud_3_Feb_2021_at_10_27_52.log.txt…]()

**Comment by jesmrec** [comment]
### (4) (improvement)

Option `Select All` is missed with the new Photo/Album picker. It'd be interesing whether exists any choice to recover it somehow.

**Comment by jesmrec** [comment]
### (5)

Fix developed here: https://github.com/owncloud/ios-app/pull/870#issue-554929848

is missed somewhere:

![Screenshot 2021-02-03 at 13 35 29](https://user-images.githubusercontent.com/14894746/106747924-d1399600-6624-11eb-9e1d-ac78ddd5518e.png)

App `8bc2d1b1`
SDK `5a70106`
iPhoneXR v14.2

**Comment by hosy** [comment]
@jesmrec (5) this cannot be fixed, because if sort key = `name` and the file list is longer than the visible area, the index bar will be shown on the right side and the cell content will get a right inset.
If you change the sort key or the file list is not so long, everything is fine.

**Comment by jesmrec** [comment]
thanks for the explanation, got it.

**Comment by felix-schwarz** [comment]
@jesmrec (1) and (2) should be fixed.

Regarding (2), the problem was this:
- `302` is not an actually supported way to redirect to a different OC root.
- instead a `302` response triggers the Connection Validator, which then got caught up in the responses.

The Connection Validator now detects that infinite loop and breaks out of it after 3 attempts. It then falls back to delivering the `302` response "as-is", like he Connection Validator did not exist.

That could mean that the `302` could end up working - but only as a lucky byproduct, not because it is supported.

**Comment by felix-schwarz** [comment]
@jesmrec Would love to look at (3), but the log file didn't complete uploading in your comment.

**Comment by jesmrec** [comment]
> @jesmrec Would love to look at (3), but the log file didn't complete uploading in your comment.

this is the log of (3), now completely uploaded

[ownCloud_3_Feb_2021_at_10_27_52.log.txt](https://github.com/owncloud/ios-app/files/5923972/ownCloud_3_Feb_2021_at_10_27_52.log.txt)

**Comment by jesmrec** [comment]
About (1) and (2), with commit `523a404` :

(1) -> with the redirected `ocis.owncloud.works`, it works fine. I have a server with redirection 301 that points to a different folder (like the 302 in the report (2) ). Is this supported? The request flow is a little strange, from my pov:

![Screenshot 2021-02-04 at 09 38 53](https://user-images.githubusercontent.com/14894746/106866533-dce09780-66cc-11eb-9f2e-82147d825143.png)

At the end, this error happens:

![Screenshot 2021-02-04 at 09 40 22](https://user-images.githubusercontent.com/14894746/106867060-7445ea80-66cd-11eb-8b00-b2df8aed39f6.png)

These are the logs:

[ownCloud_4_Feb_2021_at_09_41_10.log.txt](https://github.com/owncloud/ios-app/files/5924289/ownCloud_4_Feb_2021_at_09_41_10.log.txt)

(2) -> Regarding 302, the test server i have contains a redirection. Any other way/server to test correctly with 302?

**Comment by felix-schwarz** [comment]
@jesmrec Thanks for the log for (3)!

Re (2): That flow certainly looks unusual, but not unexpected provided the redirection is what I believe it to be… does this server redirect from `/status.php` to `/stable10/status.php` - or to `/stable10/`?

Generally:
- 302 redirects are not / no longer supported for redirecting to a different root, because that root-discovery could lead to the client getting locked out by an APM.
- unlike before, 302 redirects now trigger the Connection Validator, which is geared towards satisfying an APM's needs/requirements and then returning the connection to a controlled state.
- FYI: as part of the redirect handling overhaul `/owncloud/` auto detection has also been removed.

Replacing the 302 redirect with a 301 redirect should resolve the issue.

**Comment by felix-schwarz** [comment]
Re (3) the issue seems to be that the FP and the app attempt a token refresh in close timely proximity to each other, where the app sends the refresh request, and then the FP sends its refresh request before the app receives its response, resulting in the error. Working on a fix.

**Comment by jesmrec** [comment]
Regarding (1) and (2): that means it works only if the redirection (no matter if 301 or 302) will point to a location in root folder. Redirections to subfolders are not working. I'm not sure if that restriction is valid.  Those who use middleware could need redirections to somewhere and will be affected. Is this correct @michaelstingl ?

> How was that redirect set up? By hand - or is it a supported option in the docker image?

i set up by using these files: 

[redirect.zip](https://github.com/owncloud/ios-app/files/5926998/redirect.zip)

a `docker-compose up` will create both redirections in ports 301 and 302.

**Comment by felix-schwarz** [comment]
@jesmrec `301` redirections to subfolders should definitely work, but here the redirect targets not the subfolder, but the `status.php` in the subfolder - and I'm not sure that is / that should be supported.

`302` is reserved for BigIP/APM usage and not supported to redirect to installs in a subfolder.

**Comment by jesmrec** [comment]
ok, got it. I have tweaked a bit the redirect test server to point in this way:

`Location:        http://192.168.1.66:800/stable10`

did you mean that @felix-schwarz ? in this case, it works totally fine!

**Comment by felix-schwarz** [comment]
Yup, that's what I meant.

I haven't seen a redirect from `status.php` to the `status.php` in a subfolder before, which is why I believe that it is likely not supported. But I'm not 100% sure. Should that be supported @michaelstingl ?

**Comment by michaelstingl** [comment]
Normally you don't have `example.cloud/status.php` to `example.cloud/[subfolder]/status.php`, you normally have `example.cloud/` to `example.cloud/[subfolder]/` ?

**Comment by hosy** [comment]
### (6) Import from Share Sheet 

When I import a PDF file via Safari Share Sheet, the PDF file and another unknown item will be imported.
The unknown item should not be imported.

**Comment by jesmrec** [comment]
@hosy this is what i see when i share PDF from Safari via  share sheet. Am i missing something?

![Feb-05-2021 13-08-31](https://user-images.githubusercontent.com/14894746/107032115-9154e900-67b3-11eb-921f-6dfa00d4d763.gif)

**Comment by felix-schwarz** [comment]
> Normally you don't have `example.cloud/status.php` to `example.cloud/[subfolder]/status.php`, you normally have `example.cloud/` to `example.cloud/[subfolder]/` ?

Maybe I was wrong… looking at https://github.com/owncloud/administration/blob/master/redirectServer/Readme.md, it looks like there can also be redirects from `example.cloud/remote.php/webdav/` to `instance.cloud/remote.php/webdav/` - and possibly also `example.cloud/status.php` to `example.cloud/[subfolder]/status.php`.

**Comment by felix-schwarz** [comment]
Taking the above into account, I tweaked the implementation a bit now, so that these redirects should now all work:

From | To
-- | --
https://origin.server/status.php | https://target.server/status.php
https://origin.server/status.php | https://target.server/
https://origin.server/status.php | https://target.server/owncloud/
https://origin.server/status.php | https://origin.server/owncloud/status.php
https://origin.server/status.php | https://origin.server/owncloud/

Opening an old `ocis.owncloud.works` bookmark (pre redirection) is now also handled correctly.

**Comment by felix-schwarz** [comment]
@jesmrec @michaelstingl I added a general purpose mechanism for expiring, coordinated, cross-process-capable locks to the SDK and now OAuth2 and OIDC use it to ensure that only one process at a time starts a token refresh. That should fix (3).

**Comment by mneuwert** [comment]
> ### (4) (improvement)
> Option `Select All` is missed with the new Photo/Album picker. It'd be interesting to check whether exists any choice to recover it somehow.
> 
> Btw, it is also missing the RAW indicator. Any way to include it?

- System photo picker unfortunately doesn't allow selecting all... or select complete album..
- Also showing custom badges is the UX decision of Apple here
- We would be more flexible and could try to extend our custom photo picker, but then we would loose some features present in the official solution like e.g. search... 
- Also we could give user a choice in settings which photo picker to use but not sure if it won't unnecessarily complicate the UX

**Comment by jesmrec** [comment]
About redirections:

https://origin.server/status.php | https://target.server/owncloud/status.php | https://target.server/owncloud/
-- | -- | --

this case fits with the case reported in (1). I've tested it again and the result is the same reported [there](https://github.com/owncloud/ios-app/issues/886#issuecomment-773136707). 

app: `404d5c4`
sdk: `bad8654`

@felix-schwarz

**Comment by jesmrec** [comment]
(3) is fixed

**Comment by jesmrec** [comment]
### (7)

Sessions are lost after upgrading

1. Install 11.4.5
2. Add some bookmarks (basic, oauth2...)
3. Upgrade to 11.5

Current: all sessions are like expired. User is prompted to sign in again
Expected: sessions keep active after upgrading

app: `404d5c4`
sdk: `bad8654`

iPhoneXR v14.2
iPadAir v13

**Comment by felix-schwarz** [comment]
> About redirections:
> 
> https://origin.server/status.php	https://target.server/owncloud/status.php	https://target.server/owncloud/
> this case fits with the case reported in (1). I've tested it again and the result is the same reported [there](https://github.com/owncloud/ios-app/issues/886#issuecomment-773136707).
> 
> app: `404d5c4`
> sdk: `bad8654`
> 
> @felix-schwarz

I'm sorry, but I don't really understand. Can you elaborate a bit?

**Comment by jesmrec** [comment]
sorry @felix-schwarz, let's go with more details:

after the last fixes regarding redirections, [a set of scenarios](https://github.com/owncloud/ios-app/issues/886#issuecomment-774305553) should work, as you posted.

One of them:

From | To | Root URL
-- | -- | --
https://origin.server/status.php | https://target.server/owncloud/status.php | https://target.server/owncloud/

is the one i reported in [(1)](https://github.com/owncloud/ios-app/issues/886#issuecomment-772337148)

i have tested this one again with the last commits:

app: `404d5c4`
sdk: `bad8654`

and the result is the same as the one reported in (1):

![Screenshot 2021-02-03 at 09 41 42](https://user-images.githubusercontent.com/14894746/106720750-1d281300-6604-11eb-8479-c7f1261d77a0.png)

I've caught logs with the mentioned commits:

[ownCloud_8_Feb_2021_at_12_19_32.log.txt](https://github.com/owncloud/ios-app/files/5943300/ownCloud_8_Feb_2021_at_12_19_32.log.txt)

**Comment by felix-schwarz** [comment]
Re (7): this was caused by this piece of code in AppDelegate.swift:
```swift
VendorServices.shared.onFirstLaunch {
	OCAppIdentity.shared.keychain?.wipe()
}
```
introduced in b1f3f27.

I'm not sure what this code was meant for, so commented it out for now, as it wiped all keychain entries when updating from a version that did not yet have `firstLaunch` detection, which IIRC is anything before 11.5.

The issue should be addressed for now, but since the code certainly served a purpose, it should be reworked to avoid the issue when upgrading from a previous version without `firstLaunch` detection.  (cc @mneuwert)

**Comment by felix-schwarz** [comment]
@jesmrec Thanks for the docker test setup. As of 427de6a4a48a3f775b4771897995f3e0eef37612 redirections should now work as intended.

Testing with your test setup, I also discovered that not everywhere the port number was taken into account when determining if a redirection targets a different or the same host. It now is, so that the `302` redirect to a different port number fails immediately and no longer invokes the Connection Validator (the CV requires scheme/host and port to be identical in a redirection before following them), leading to a prompter error response.

**Comment by hosy** [comment]
@jesmrec regarding (6) this is not an app issue. Just check it with other sources and it is working fine. (6) is no longer an issue from my side.

**Comment by mneuwert** [comment]
> Re (7): this was caused by this piece of code in AppDelegate.swift:
> 
> ```swift
> VendorServices.shared.onFirstLaunch {
> 	OCAppIdentity.shared.keychain?.wipe()
> }
> ```
> 
> introduced in [b1f3f27](https://github.com/owncloud/ios-app/commit/b1f3f27f87e3881d9c7df05f86492a6b5cf8b188).
> 
> I'm not sure what this code was meant for, so commented it out for now, as it wiped all keychain entries when updating from a version that did not yet have `firstLaunch` detection, which IIRC is anything before 11.5.
> 
> The issue should be addressed for now, but since the code certainly served a purpose, it should be reworked to avoid the issue when upgrading from a previous version without `firstLaunch` detection. (cc @mneuwert)

If you delete an app on iOS > 10.2, everything but keychain entries created by the app is lost. So the intention of this change was to make sure that if the app is reinstalled, it is in the consistent state. There is also a related OWASP finding. But my thinking apparently was to short in regards to backwards-compatibility. I think we shall add some sort of minimum version check here.

**Comment by felix-schwarz** [comment]
@mneuwert Thanks for the explanation!

No matter what version the app checks for, there will always be people who don't update for a long time - and then get their account's login data deleted when making a big jump to the latest version.

So instead of checking for versions + first launch alone, I'd propose to check for a combination of these:
- zero bookmarks (-> 100% certainty no needed account secrets will be deleted)
- first launch
- passcode not enabled (because if it is, it's not the first launch - and a keychain wipe could remove the passcode as well)

… and only if they all happen at the same time, perform a keychain wipe.

**Comment by jesmrec** [comment]
(7) is fixed. After upgrading from 11.4.5, user is not prompted to sign in anymore.

**Comment by jesmrec** [comment]
### (8)

While testing (7), i detected this one. Check these steps out:

1. Install 11.4.5
2. Open `Settings` and check that `Logging` is enabled
3. Upgrade to 11.5
4. Open `Settings`

Current: `Logging`  is off
Expected: `Logging`  is on, with the proper setup

app: `a8252d6`
sdk: `ef4fbfc`
iPhoneXR v14.2
iPadAir v13.4

**Comment by felix-schwarz** [comment]
@jesmrec Re (8): The log setting should actually be migrated from 11.4.5 (where it is stored in user defaults) to 11.5 (where it is stored through class settings) - however only once. So if you launched a copy of 11.5 before without erasing the app, it will not run migration again.

Can you please verify this issue also occurs when:
- deleting the app from the device (to remove any trace of a previous migration)
- installing 11.4.5
- enable logging
- run 11.5 the first time

**Comment by felix-schwarz** [comment]
@jesmrec Nevermind, I found a way for migration to fail even when following the above. I will provide a fix shortly.

**Comment by jesmrec** [comment]
Steps done:

1. Remove the app from the device
2. Switch the device off and then, switch it on again (so, we are sure everything is completely removed)
3. Install 11.4.5 (app `e53f2cd`  sdk  `95bbb2e`)
4. Open `Settings`.  `Logging` is enabled just after install by default. All switches are on, and `Error` is set as log level
5. Install 11.5  (app: `a8252d6` sdk: `ef4fbfc`). I used an archived ipa, installed in the device with Xcode -> Window -> Devices & Simulators -> Drag ipa inside the device.
6. when installation finished, open app and  `Settings`

`Logging` is off. 

This is the only setting with bad value. All the remaining settings are in the correct value (tested in the scope of the test plan)

**Comment by jesmrec** [comment]
> @jesmrec Nevermind, I found a way for migration to fail even when following the above. I will provide a fix shortly.

i posted at the time the steps i did. If they can help... 

let me know when it's done. Thanks!

**Comment by felix-schwarz** [comment]
@jesmrec Sorry! (8) should be fixed now.

**Comment by jesmrec** [comment]
Unfortunately, app `4004cbb` and sdk `6ae3031` did not fix the problem. Let me know if you need something else. Were you able to reproduce?

The question is, if this issue should be or not a release-blocker. CC @michaelstingl

**Comment by michaelstingl** [comment]
> The question is, if this issue should be or not a release-blocker. CC @michaelstingl

not a release-blocker 👍

**Comment by felix-schwarz** [comment]
@jesmrec I just found that `11.4.5` already used class settings to store the log level, but in `log.log-level` instead of `log.level`. So I added a migration path for that location as well. Now it should work from all previous versions.

**Comment by jesmrec** [comment]
(8) is fixed

**Comment by jesmrec** [comment]
11.5 is approved on my side

App approved commit: `f4bd3194`
SDK approved commit: `d38faca`

Xcode version: `12.2 (12B45b)`

Some release notes:

- Dynamic client registration works in the first stage (`client_id` and `secret_id` are granted). The existing test idP makes them expire after 1h, so the user must login again. Problem to fix in idP as https://github.com/owncloud/openidconnect/issues/142

- Redirections were tested with severs that also contain a subfolder. 301 redirections could be also tested in `ocis.owncloud.works`,  and it'd be interesting to have a server/environment to test 302 with server in root.
