### ISSUE TITLE
File list

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#9]
Features to support in the file list:

- [x] Design cell in file list [DONE] https://github.com/owncloud/ios-app/pull/28
- [x] Show the list of files from PROPFIND [DONE] https://github.com/owncloud/ios-app/pull/28
- [x] Distinguish in any way file and folders [DONE] https://github.com/owncloud/ios-app/pull/28
- [x] Browsability, forwards and backwards [DONE] https://github.com/owncloud/ios-app/pull/28
- [x] Set icons for different kind of files [DONE] https://github.com/owncloud/ios-app/pull/28
- [x] Thumbnails for pics and videos if server supported [DONE]
- [x] Sort methods [DONE]
- [x] Refreshing view [DONE] https://github.com/owncloud/ios-app/pull/28
- [x] Set amount of files/folders on the bottom of the list
- [x] More than 20 items, divide the list by letters if the sort is alphabetically
- [x] Filtering 
- [x] Figma screenhots opened to discussion
- [x] drag & drop to interact with other apps

This is an epic, smaller issues will be created to develop in an incremental way

**Comment by michaelstingl** [comment]
added _drag & drop to interact with other apps_

**Comment by michaelstingl** [comment]
Some thoughts:

User interaction should feel "native". With iOS 11, the Files app is the standard for users to interact with files. Users will interact with oC data in the Files app and in the oC iOS app itself. It would be weird if they would behave very different. (btw I really don't like the long-press behaviour in the Files app)

On the other hand, it would be cool if some things are consistent across all platforms. Icons could be such a thing. I started to add the icons from oC server to the Figma prototype: 

![image](https://user-images.githubusercontent.com/214010/37827338-543c579a-2e97-11e8-8a1d-0657c56e3cfe.png)

Source:
https://github.com/owncloud/core/tree/master/core/img/filetypes
