### ISSUE TITLE
[RELEASE] 11.6.0

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#953]
Release a new version

Xcode version to work with:
12.5

### Git & Code

- [x] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [x] [TRFX] Update translations from transifex branch.
- [x] [TRFX] Check for missing translations. Ping @cscherm
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [DEV] Update In-App Release Notes (changelog) in ownCloud/Release Notes/ReleaseNotes.plist
- [x] [DEV] Changelog: Created a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD
- [x] [DEV] Changelog: Moved all changelog files from the unreleased folder to the new version folder
- [x] [QA] Design Test plan
- [X] [QA] Regression Test plan
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [ ] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

If it is required to update the iOS-SDK version:

- [x] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code)
- [ ] [mail] inform #marketing about the new release.
- [ ] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [x] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [ ] [DIS] Upload the binary to the App Store
- [ ] [DIS] App Store Connect: Trigger release (manually)
- [ ] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [ ] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [ ] [DIS] App Store Connect: Update changelogs
- [ ] [DIS] App Store Connect: Submit for review

## QA

Regression test: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2011.6/Regression_11.6.md

Bugs & improvements:

- [x] (1) Help web is missing https://github.com/owncloud/ios-app/issues/953#issuecomment-832513960 [FIXED]
- [x] (2) Media player control is to near to the bottom https://github.com/owncloud/ios-app/issues/953#issuecomment-832686703 [FIXED]
- [x] (3) Light background in dark mode docx files https://github.com/owncloud/ios-app/issues/953#issuecomment-832769622 [NOT A BUG]
- [x] (4) https://github.com/owncloud/ios-app/issues/953#issuecomment-832884845 [NO REPR]
- [x] (5) pptx thumbnails overlapped by the notch https://github.com/owncloud/ios-app/issues/953#issuecomment-833297731 [FIXED]
- [X] (6) Crash in different options in PDF preview in iPad https://github.com/owncloud/ios-app/issues/953#issuecomment-833405411  [FIXED]
- [x] (7) Glitch in presentation mode https://github.com/owncloud/ios-app/issues/953#issuecomment-833512126 [FIXED]
- [X] (8) Selected row in file list https://github.com/owncloud/ios-app/issues/953#issuecomment-833522581 [MOVED TO [#967](https://github.com/owncloud/ios-app/issues/967)]
- [X] (9) Server list nor refreshing https://github.com/owncloud/ios-app/issues/953#issuecomment-833832214  [FIXED]
- [x] (10) Accessibility checks https://github.com/owncloud/ios-app/issues/953#issuecomment-836529460s
- [X] (11) iOS 12 checks https://github.com/owncloud/ios-app/issues/953#issuecomment-836583002
- [x] (12) Crash in folder picker https://github.com/owncloud/ios-app/issues/953#issuecomment-836640160 [FIXED]
- [X] (13) Label does not fit the screen width https://github.com/owncloud/ios-app/issues/953#issuecomment-836682956 [FIXED]

**Comment by jesmrec** [comment]
### (1)

not a bad behaviour of the app, but needs to be checked somehow

1. Open Settings
2. Click on `Help`

Current: 404 
Expected: a correct help web

iPhoneXR v14.4
`6adc653a`

**Comment by hosy** [comment]
@jesmrec (1) is fixed in https://github.com/owncloud/ios-app/pull/915/commits/de83cc497105ba1ab5085c39a555a95b18e0e514

**Comment by ChrisEdS** [comment]
### (2) Media player control is to near to the bottom

#### Steps to reproduce
1. Upload a MP3 file
2. Click on it

#### Current behaviour (on iPhone 11)
The media control panel is too near at the bottom, when you try to use the scrubber it happens that you trigger the app switcher instead

![image](https://user-images.githubusercontent.com/33026403/117148200-4d737f00-adb6-11eb-9594-d7a3f5862278.png)

#### Expected behaviour
Add more spacing to the bottom

**Comment by jesmrec** [comment]
### (3)

This could be related with this: https://github.com/owncloud/ios-app/issues/919

1. Set Dark theme
2. Open a docx file

Current: White background
Expected: Dark background

iPhoneXR v14.4
`43e072c6`

**Comment by hosy** [comment]
(4) Preview Controller does not show any content (doc, txt, md, xls, ...)

**Comment by jesmrec** [comment]
### (5)

1. Open a pptx file in landscape orientation in a device with notch, like iPhone XR

Current: thumbnails are overlapped by the notch

![IMG_20210506_091704](https://user-images.githubusercontent.com/14894746/117258445-477cad00-ae4d-11eb-9b5a-290c383e579a.jpg)

iPhoneXR v14.4
`de83cc49`

**Comment by jesmrec** [comment]
### (6)

Reproduced with an iPad with iOS13 and iPad simulator with iOS14.5

1. Preview a PDF file
2. Click on the lens icon (search) or the index icon on the bottom side of the screen

Current: app crashes
Expected: no crash

`de83cc49`
iPadAir v13.4

**Comment by hosy** [comment]
@jesmrec (2) (5) (6) are fixed in https://github.com/owncloud/ios-app/pull/915/commits/f9071458c267e152c95d88e099233bfc69b15018

(3) can not reproduced. Please can you share a document and screenshot
(4) can no longer reproduced on simulator

**Comment by hosy** [comment]
@jesmrec (6) sorry, still appears. Is a little bit strange and I will have a look.

**Comment by jesmrec** [comment]
### (7)

An small glitch 

1. Using an iPad, open a txt file
2. Enable presentation mode

Current: top line of the file collides with the info device:

https://user-images.githubusercontent.com/14894746/117303809-698e2380-ae7d-11eb-9863-b49de1a97f35.MP4

iPadAir v13.4
`de83cc49`

**Comment by hosy** [comment]
@jesmrec (6), (7) are fixed in https://github.com/owncloud/ios-app/pull/915/commits/4a3d973d603314f6a9af4963573893b8bf529e27

**Comment by hosy** [comment]
### (8) Selected Row in File List

on iPad with hardware keyboard:
- select a row in the file list with the keyboard down key
- after a short time the selection gets lost

Expected Result:
File list keeps selection

**Comment by hosy** [comment]
### (9) Server List not refreshing

Deleting or adding a bookmark with keyboard shortcut does not refresh the server list.

**Comment by jesmrec** [comment]
(1), (2) fixed

(3) This is the file:

[office2018.docx](https://github.com/owncloud/ios-app/files/6439521/office2018.docx)

And the scenario:

https://user-images.githubusercontent.com/14894746/117408075-b4f11200-af0f-11eb-92ec-64850514e140.MP4

(4) no reproducible
(5) fixed
(6) Lens icon crash is fixed. Index icon crash is still reproducible
(7) fixed

**Comment by hosy** [comment]
@jesmrec 
(3) is the expected behavior, because this is the background color of the document. To check the theming for documents, please use a plain text or markdown file, which has no document background color.

**Comment by jesmrec** [comment]
ok, i had also this doubt... but justo to be sure i wrote the report. I will mark as expected

**Comment by hosy** [comment]
@jesmrec (5) and (9) are fixed with commit https://github.com/owncloud/ios-app/pull/915/commits/8733c755a87ba0b84c77776dc559abd24ab0f719

**Comment by hosy** [comment]
@jesmrec (8) needs to be fixed in a new release. I added an issue for that: https://github.com/owncloud/ios-app/issues/967

**Comment by jesmrec** [comment]
### (9)

Accessibility checks with VoiceOver. New features in the release:

- [X] Go to Page in PDF Card actions 
- [X] Presentation mode in Card actions
- [X] Presentation mode dialog 
- [ ] Presentation mode actions -> not posible to dismiss full screen
- [ ] Thumbnails in PDF -> not swiping
- [X] Conflict dialog 
- [ ] Search ownCloud, Select Account/Folder -> does not work, only spelling the sorting options that are behind
- [X] Search ownCloud, Type some criteria

**Comment by hosy** [comment]
> ### (10)
> Accessibility checks with VoiceOver. New features in the release:
> 
> * [x]  Go to Page in PDF Card actions
> * [x]  Presentation mode in Card actions
> * [x]  Presentation mode dialog
> * [ ]  Presentation mode actions -> not posible to dismiss full screen
I will have a look how it could be solved

> * [ ]  Thumbnails in PDF -> not swiping (posible in VoiceOver mode?)
It is possible:
- Tap on Thumbnails (Element will be highlighted)
- Swipe up for next page
- Swift down for previous page

> * [x]  Conflict dialog
> * [ ]  Search ownCloud, Select Account/Folder -> not working, only is spelling the sorting options behind
This is an iOS problem. The search tab bar is not visible in portrait mode, but iOS still provides the accessibility from the hidden tab bar, which overlays over the search scope button. Not sure, if we can provide a fix for that.


> * [x]  Search ownCloud, Type some criteria

**Comment by jesmrec** [comment]
> > ### (10)
> > Accessibility checks with VoiceOver. New features in the release:
> > 
> > * [x]   Go to Page in PDF Card actions
> > * [x]   Presentation mode in Card actions
> > * [x]   Presentation mode dialog
> > * [ ]   Presentation mode actions -> not posible to dismiss full screen
> 
> I will have a look how it could be solved

Thanks! let me know if the fix is feasible!

> 
> > * [ ]   Thumbnails in PDF -> not swiping (posible in VoiceOver mode?)
> 
> It is possible:
> 
> * Tap on Thumbnails (Element will be highlighted)
> * Swipe up for next page
> * Swift down for previous page

Thanks, it works. Marked as OK
 
> > * [x]   Conflict dialog
> > * [ ]   Search ownCloud, Select Account/Folder -> not working, only is spelling the sorting options behind
> 
> This is an iOS problem. The search tab bar is not visible in portrait mode, but iOS still provides the accessibility from the hidden tab bar, which overlays over the search scope button. Not sure, if we can provide a fix for that.
> 

OK, no problem. I know that this is not the first time that this kind of error happens. Let's wait a bit more for a platform fix. This will not block the release. 

> > * [x]   Search ownCloud, Type some criteria

**Comment by hosy** [comment]
@jesmrec (13) is fixed in https://github.com/owncloud/ios-app/pull/915/commits/4ae752d61b63b6c2474b97d923a0b6c1d837883a

**Comment by jesmrec** [comment]
(10) -> fixed. I will open issue for the fullscreen mode in accesibility.
(12) -> fixed
(13) -> fixed

**Comment by jesmrec** [comment]
All tests passed. Release approved on my side

Commits approved:

app: `42a88f8`
sdk: `0188f4f`
Xcode version: `12.5 (12E262)`

Great job, team!! awesome release!!
